# Securitisation Lexicons Creation
This notebook contains the pipeline I use for creating the intial 3 lexicons capturing to the 3 dimensions of Securitisation Theory (Buzan et al, 1998), namely Threat, Urgency and Justification of Extraordinary Power. This feeds off one of Securitisation Theory's core concepts, that security isn't just a state of being but a performative act.

I ground this pipeline in an academically validated approach where I begin with seed words extracted from illlustative examples from foundational securitisation literature and then expand with relevant well-established lexicons, and finally grow it further using SBERT to find similar words used in similar contexts across the manifesto corpus. The result at the end of this pipeline is a transparent and theoretically grounded set lexicons capturing securitisation theory in its 3 consistutent parts.

In [1]:
#!pip install pyspellchecker inflect wordfreq xlsxwriter spellchecker
import string
from spellchecker import SpellChecker
import pandas as pd
import sys
import inflect
import wordfreq

# 1. Seed Words
Securitisation Theory is heavily based on discursive patterns and language purpose, so the formation of seed terms for each dimension will be reliant on a contextual inference process (as with Baele & Rousseau, 2022) where I choose words chosen from key examples in securitisation literature.

One thing not accounted for is pronouns. These could maybe tell an interesting story, like the use of "we" to unify the speaker with the audience, and "they" to discriminate certain groups. There is room to explore this in future work.

### 1a. Initial Lists Creation from Literature
Firstly the initial terms and phrases from the literature are extracted and supplemented with my own understanding of Securitisation Theory. Importantly these include words and phrases commonly utilised in securitising stylistic devices like metaphors (e.g. "wave" and "a cancer") and historical references (e.g. "9/11", "Blitz") (Baele & Rousseau, 2022). The former can give a simplified understanding which warrants a specific course of action and triggers certain emotions, and the latter projects a simplified version of a past event onto the present to unify the speaker with the audience and provide a course of actions based on past learning.

The following terms have been organised alphabetically for easy lookup if used in later work.

In [2]:
# Terms taken from: Buzan et al. (1998), (Otukoya (2024), Baele & Rousseau (2022)
threat_seed_lexicon_words= {
"7/7", "9/11", "abm", "aegis", "afghanistan", "aggression", "airpower", "alqaeda", "antipersonnel", "arab", "armament", "armaments",
"armies", "arming", "armory", "armour", "armoured", "armoury", "arms", "army", "assassin", "assassinate",
"assassinated", "assassinating", "assassination", "assassinations", "assassins", "assault", "atomic", "attack",
"attacked", "attacker", "attackers", "attacking", "attacks", "authority", "ballistic", "barbarian",
"barbarians", "battle", "biological", "blitz", "blockade", "blockaded", "blockades", "blockading", "blocked",
"blocks", "bombard", "bombarded", "bombarding", "bombardment", "bombardments", "bombards", "bombed", "bomber",
"bombers", "bombing", "bombings", "bombs", "bombshell", "bombshells", "brutal", "bullet", "capitulate",
"capitulated", "capitulating", "capitulation", "casualties", "casualty", "catastrophe", "catastrophes",
"catastrophic", "catastrophically", "chechnya", "chemical", "cluster", "coerce", "coerced", "coercing",
"coercion", "coercive", "colonial", "combat", "combatant", "combatants", "combated", "combating", "combats",
"combatting", "conflict", "conflicts", "counterfeit", "counterfeits", "coup", "crime", "crimea", "crimean",
"crimes", "criminal", "criminalisation", "criminalise", "criminalised", "criminalization", "criminalize",
"criminalized", "criminalizes", "criminalizing", "criminally", "criminals", "crisis", "cybersphere", "cyberwar",
"daesh", "death", "deaths", "demise", "demises", "destabilise", "destabilising", "destabilization",
"destabilize", "destabilized", "destabilizing", "destructed", "destructible", "destruction", "destructions",
"destructive", "destructively", "destructor", "deteriorate", "deteriorated", "deteriorates", "deteriorating",
"deterioration", "dictator", "disaster", "disease", "disintegrate", "disintegrated", "disintegrates",
"disintegrating", "disintegration", "disobedience", "disobedient", "division", "dominance", "dominant",
"dominantly", "dominate", "dominates", "dominating", "domination", "dominator", "dominators", "drowning",
"drownings", "drugs", "enemies", "enemy", "espionage", "espionages", "evil", "existential", "explosion",
"explosions", "explosive", "explosively", "explosives", "extinction", "extinctions", "extremism", "extremisms",
"extremist", "extremists", "faction", "fatalities", "fatality", "fighter", "fighters", "fighting", "fights",
"firearms", "fln", "forceful", "forcefully", "forces", "fragile", "fundamentalism", "fundamentalist",
"fundamentalists", "gang", "gaza", "genocide", "grave", "guerrilla", "guevara", "gulf", "hamas", "hazard",
"hazardous", "hazards", "hegemonic", "hegemony", "hezbollah", "hiroshima", "hostile", "hostiles", "hussein",
"illegal", "illegality", "illegally", "illegals", "illicit", "infiltrate", "infiltrated", "infiltrates",
"infiltrating", "infiltration", "infiltrations", "infiltrator", "infiltrators", "inhuman", "insecure",
"insecurities", "insecurity", "insurgencies", "insurgency", "insurgent", "insurgents", "interpol", "invaded",
"invader", "invaders", "invades", "invading", "invasion", "invasions", "ira", "iran", "iraq", "islamic",
"islamist", "israel", "israeli", "israelis", "israelite", "israelites", "israels", "killed", "killer",
"killers", "killing", "killings", "kills", "killswitch", "killzone", "kurd", "kurdish", "kurdistan", "kurds",
"landmine", "lawbreakers", "lawless", "lawlessness", "lebanon", "libya", "menace", "menaces", "militaries",
"militarisation", "militarised", "militarism", "militarist", "militaristic", "militarization", "militarized",
"military", "missile", "monster", "monsters", "munitions", "muslims", "nagasaki", "narcotics",
"nationalisation", "nationalist", "nationalistic", "nationalists", "nato", "nazi", "netwar", "nuclear", "osce",
"pakistan", "palestine", "partisan", "peril", "perils", "proliferating", "proliferation", "racism", "racist",
"racists", "radicalisation", "radicalise", "radicalised", "radicalising", "radicalism", "radicalization",
"radicalize", "radicalized", "radicalizing", "radicals", "repressive", "rival", "rivals", "rogue", "ruthless",
"rwanda", "rwandan", "salw", "salwar", "sarin", "seapower", "securities", "separatism", "separatist",
"separatists", "shock", "shortage", "somalia", "strike", "suicide", "superpower", "surveillance", "survival",
"syria", "target", "terminated", "termination", "terror", "terrorise", "terrorised", "terrorising", "terrorism",
"terrorist", "terroristic", "terrorists", "terrorize", "terrorized", "terrorizes", "terrorizing", "terrors",
"threat", "threaten", "threatened", "threatening", "threateningly", "threatens", "threats", "trafficked",
"trafficker", "traffickers", "trafficking", "traffics", "uprising", "vicious", "vietnam", "violence", "violent",
"violently", "virus", "viruses", "vulnerabilities", "vulnerability", "vulnerable", "vulnerables", "war",
"warfare", "warfield", "warfighter", "warfighting", "wargame", "wargames", "warhead", "warheads", "warmonger",
"warmongering", "warmongers", "warpath", "warplane", "warplanes", "wars", "wartime", "wave", "waves",
"weaponise", "weaponised", "weaponize", "weaponized", "weaponry", "weapons", "wmd", "wound", "wounded",
"wounding", "wounds"}

threat_seed_lexicon_terms= {"a cancer", "arm industry", "at war", "at wars", "being radicalised", "cogs of war", "cogs of wars", "day slavery", "engine of war",
"existential threat", "existential threats", "fight back", "fuel conflicts", "illegal immigrant",
"illegal immigrants", "illegal migrant", "illegal migrants", "invisible enemies", "invisible enemy",
"new verdun", "new verduns", "nine eleven", "nine-eleven", "our threat", "pearl harbor", "prisoners of",
"sea power", "sea powers", "security priorities", "serious threat", "serious threats", "seven seven",
"seven-seven", "the troubles", "toxic legacies", "under attack", "under attacks", "war engine", "war engines",
"war machine", "war machines", "war on", "wars on", "world war", "world wars"}

In [3]:
# Terms taken from: Buzan et al. (1998), Otukoya (2024), Ahmad (2025), Baele & Rousseau (2022)
urgency_seed_lexicon_words= {"armageddon", "collapse", "collapsed", "collapses", "collapsing", "crises", "crisis", "critical", "demand", "emergency", "ensure",
"escalate", "escalating", "escalation", "immediate", "immediately", "imminent", "imminently", "inevitabilities",
"inevitability", "inevitable", "irreversible", "mounting", "overdue", "overrun", "paramount", "react",
"reaction", "reactions", "reacts", "scarce", "scarcely", "scarcity", "spiralling", "swift", "tackle",
"unparalleled", "unprecedented", "urgent", "urgently", "worsening"}

urgency_seed_lexicon_terms= {"act now", "any longer", "before the election", "breaking point", "can't delay", "can't wait", "cannot afford", "cannot delay",
"cannot wait", "decisive action", "decisive actions", "end degrading", "from day one", "growing crisis",
"immediate action", "immediate actions", "last chance", "life threatening", "life-threatening", "make sure",
"move quickly", "move rapidly", "move swiftly", "must not delay", "mustn't delay", "national crisis",
"now or never", "on day one", "point of no return", "push to", "quickly move", "quickly moves", "rapidly move",
"rapidly moves", "strive for", "supreme priorities", "supreme priority", "swiftly move", "swiftly moves",
"threatening crisis", "ticking clock", "tipping point", "too late", "urgent priorities", "urgent priority",
"wakeup call", "without delay"}

In [4]:
# Terms taken from: Buzan et al. (1998), Otukoya (2024), State of exception (2003), Flohr (2025)
justification_of_extr_power_seed_lexicon_words= {"abate", "abatement", "abolish", "abolition", "anarchy", "armistice", "ceasefire", "compelling", "compels", "compromise", "concession",
"conciliation", "conciliatory", "containment", "controlling", "controls", "cooperate", "cooperated",
"cooperates", "cooperating", "cooperation", "counteracts", "counterattack", "counterattacks",
"counterinsurgency", "counterinsurgent", "counterterrorism", "countervail", "countervailing", "crackdown",
"crackdowns", "curb", "curfew", "curfews", "decree", "decrees", "defend", "demand", "deport", "deported",
"deter", "deteriorating", "deterred", "deterrence", "detterence", "detterent", "detterents", "disarmament",
"disarmed", "disarming", "disarms", "détente", "embargo", "enforce", "enforcement", "expedite", "forbid",
"forbidden", "forbidding", "forbids", "forced", "halt", "halting", "homeland", "hostage", "interdependence",
"interdependent", "interdiction", "intervene", "intervention", "introduce", "lawfully", "liberate", "liberated",
"liberates", "liberating", "liberation", "liberator", "liberators", "lockdown", "lockdowns", "mobilise",
"mobilises", "mobilize", "mobilizes", "monitor", "nonproliferation", "overdue", "overhaul", "oversee", "powers",
"preempt", "preempted", "preemption", "preemptive", "preemptively", "prerogative", "prerogatives", "prevent",
"preventable", "preventative", "preventing", "prevention", "preventive", "protect", "protection", "protections",
"protective", "protectively", "protector", "protectorate", "protectorates", "protectors", "protects",
"punitive", "remove", "rescue", "resist", "resistance", "resistances", "resisted", "resisting", "retaliate",
"retaliation", "revenge", "sanction", "sanctioned", "sanctioning", "sanctions", "securities", "security",
"securitys", "siege", "sieges", "sovereign", "sovereigns", "sovereignty", "stabilise", "stabilised",
"stabilising", "surveil", "surveillance", "surveillances", "surveils", "suspension", "suspensions", "tackle",
"tactical", "tactically", "tactician", "tactics", "toughen", "toughened", "toughening", "uncooperating",
"uncooperative", "worsening"}

justification_of_extr_power_seed_lexicon_terms= {"age limits", "age verification", "beyond politics", "border closure", "border closures", "break free", "breaking free", "can't accept",
"can't wait", "cannot wait", "close our border", "close our borders", "close the border", "close the borders",
"commander in chief", "commander-in-chief", "commanders-in-chief", "counter attack", "counter attacks",
"counter-attack", "counter-attacks", "crack down", "crack downs", "decisive action", "decisive actions",
"don't accept", "exceptional means", "exceptional measure", "exceptional measures", "extraordinary means",
"extraordinary measures", "fast track", "fight back", "maintain order", "martial law", "martial laws",
"not accept", "protect frontline", "protecting people", "restore order", "shut our border", "shut our borders",
"shut the border", "shut the borders", "solemn duties", "solemn duty", "state of emergencies",
"state of emergency", "stop brexit", "stop the boats", "stronger control", "stronger controls", "subject to",
"ticking clock", "tipping point", "tougher sentencing", "without delay", "won't accept"}

### 1b. Validation
All seed words above were manually entered by myself. Therefore, validation is needed to ensure they're in the correct format for subsequent pipeline steps.

In [5]:
# Ensure I spell all words correctly
spell_check_lexicon_words= SpellChecker()

# I 100% need British spellings too as these are UK manifestos
words_i_explicitly_correct= {'mobilise', 'mobilize', 'lockdown', 'counter-attack', 'lockdowns', 'espionages', 'invadings', 'vulnerables', 'new verduns',
                                 'counter-attacks', 'surveillances', 'mobilises', 'surveil', 'surveils', 'inevitabilities'}
spell_check_lexicon_words.known(list(words_i_explicitly_correct))

# i setup this helper-function to go through & systematically correct misspelt lexicon terms given one of the lexicons
def spell_check_and_correct_lexicon_words(lexicon_set, lexicon_name, explicitly_correct_words):
    lex_corrected_terms= set()
    misspelled_lex_terms= {}
    print(f"\n now spell checking for {lexicon_name}...")
    for term in lexicon_set:
        if term is None:
            continue # (if this crashed on None it has to be skipped)

        # I check if the entire term (single word or phrase) is explicitly accepted in the british spellings I note
        # If so I add it as is and skip further correction attempts.
        if term in explicitly_correct_words:
            lex_corrected_terms.add(term)
            continue

        # this section is for handling multi-word terms
        if ' ' in term:
            corrected_phrase_words= []
            original_words= term.split()
            lexicon_phrase_misspelled= False
            for word in original_words:
                # here I check if individual word in phrase is explicitly accepted for british spelling
                if word in explicitly_correct_words:
                    corrected_word= word
                else:
                    corrected_word= spell_check_lexicon_words.correction(word)
                    if corrected_word is None: # I have this fallback in the case of no correction needed
                        corrected_word= word
                        
                if corrected_word != word:
                    lexicon_phrase_misspelled= True
                corrected_phrase_words.append(corrected_word)
            corrected_term_str= ' '.join(corrected_phrase_words)

            if lexicon_phrase_misspelled:
                misspelled_lex_terms[term]= corrected_term_str
                lex_corrected_terms.add(corrected_term_str)
            else:
                lex_corrected_terms.add(term)
        # and now i do the same for single words
        else:
            corrected_word= spell_check_lexicon_words.correction(term)
            if corrected_word is None:
                corrected_word= term

            if corrected_word != term:
                misspelled_lex_terms[term]= corrected_word
                lex_corrected_terms.add(corrected_word)
            else:
                lex_corrected_terms.add(term)

    if misspelled_lex_terms:
        print(f"the misspelled words in {lexicon_name} are: {misspelled_lex_terms}")
        print(f"so the corrected ones in {lexicon_name} were: {lex_corrected_terms}")
    else:
        print(f"there's actually no misspelled words found in the {lexicon_name}.")
    return lex_corrected_terms

In [6]:
# this is a validation barrier I setup to ensure all seed terms are correctly formatted i.e. no capitilisation and punctuation, + correct spellings.
def validate_lexicon_entries(lexicon_set, lexicon_name, words_i_explicitly_correct):
  spell_check_and_correct_lexicon_words(lexicon_set, lexicon_name, words_i_explicitly_correct)
  for lex_entry in lexicon_set:
    lex_entry= lex_entry.lower()
    lex_entry= lex_entry.translate(str.maketrans('', '', string.punctuation))
  print(f"Great, the {lexicon_name} lexicon is now all validated.")

# now I just run that validation barrier on all the lexicon words & terms
validate_lexicon_entries(threat_seed_lexicon_words, "threat_seed_lexicon_words", words_i_explicitly_correct)
validate_lexicon_entries(threat_seed_lexicon_terms, "threat_seed_lexicon_terms", words_i_explicitly_correct)
validate_lexicon_entries(urgency_seed_lexicon_words, "urgency_seed_lexicon_words", words_i_explicitly_correct)
validate_lexicon_entries(urgency_seed_lexicon_terms, "urgency_seed_lexicon_terms", words_i_explicitly_correct)
validate_lexicon_entries(justification_of_extr_power_seed_lexicon_words, "justification_of_extr_power_seed_lexicon_words", words_i_explicitly_correct)
validate_lexicon_entries(justification_of_extr_power_seed_lexicon_terms, "justification_of_extr_power_seed_lexicon_terms", words_i_explicitly_correct)

 now spell checking for threat_seed_lexicon_words...
the misspelled words in threat_seed_lexicon_words are: {'armoured': 'armored', 'wargames': "wagram's", 'criminalisation': 'criminalization', 'fln': 'fun', 'nato': 'nate', 'seapower': 'empower', 'warfield': 'garfield', 'extremisms': 'extremists', 'armoury': 'armour', 'militarised': 'militarized', 'terrorising': 'terrorizing', 'terrorise': 'terrorist', 'israelites': 'israelite', 'militarisation': 'militarization', 'terrorised': 'terrorized', 'dominators': 'dominator', 'wmd': 'wed', 'weaponized': 'caponized', 'radicalised': 'radicalized', 'alqaeda': 'alfreda', 'netwar': 'near', 'criminalise': 'criminalist', 'destabilising': 'destabilizing', 'osce': 'once', 'salwar': 'solar', 'destabilise': 'destabilize', 'criminalised': 'criminalized', 'abm': 'am', 'kurds': 'turds', 'weaponise': 'weapons', 'sarin': 'satin', 'wargame': 'warfare', 'daesh': 'dash', 'radicalisation': 'radicalization', 'radicalise': 'radicalism', 'weaponize': 'caponize', 'nationalisation': 'nationalization', 'destructions': 'destruction', 'radicalising': 'radicalizing', 'salw': 'saw'}
so the corrected ones in threat_seed_lexicon_words were: {'suicide', 'killed', 'disintegration', 'gulf', 'strike', 'warmongers', 'bombed', 'kurdish', 'crimes', 'surveillance', 'warheads', 'bullet', 'brutal', 'nationalist', 'capitulating', 'casualties', 'arming', 'drugs', 'faction', 'destructible', 'traffickers', 'wars', 'blockade', 'gang', 'infiltrations', 'rivals', 'threatens', 'conflict', 'attack', 'assault', 'invaders', 'racist', 'violent', 'destruction', 'violently', 'militarized', 'ruthless', 'trafficker', 'radicalize', 'coercing', 'armored', 'munitions', 'warplane', 'invader', 'target', 'catastrophic', 'invading', 'chechnya', 'monster', 'invaded', 'combatant', 'explosives', 'destabilizing', 'assassins', "wagram's", 'combatting', 'rwandan', 'radicalization', 'terror', 'viruses', 'bombarding', 'shortage', 'menaces', 'blockading', 'hezbollah', 'dominate', 'deteriorates', 'criminalized', 'racism', 'saw', 'caponized', 'bombardments', 'threat', 'warhead', 'blockades', 'israel', 'espionages', 'atomic', 'armory', 'disease', 'espionage', 'fundamentalism', 'infiltrates', 'dominant', 'killswitch', 'hiroshima', 'catastrophically', 'vulnerable', 'hazardous', 'hazard', '9/11', 'colonial', 'wounding', 'threaten', 'am', 'separatists', 'garfield', 'bombings', 'inhuman', 'survival', 'criminalizes', 'attacking', 'capitulate', 'trafficked', 'dominates', 'solar', 'disintegrate', 'israels', 'proliferating', 'insurgent', 'criminally', 'capitulation', 'destructive', 'criminalization', 'cyberwar', 'threatened', 'israeli', 'assassinate', 'deteriorating', 'shock', 'biological', 'nagasaki', 'disintegrating', 'warpath', 'dominator', 'destabilized', 'israelite', 'forcefully', 'syria', 'dominance', 'insecurity', 'rogue', 'uprising', 'catastrophes', 'partisan', 'drownings', 'wed', 'turds', 'arab', 'terrorized', 'perils', 'dash', 'armaments', 'wounds', 'warplanes', 'libya', 'extremist', 'narcotics', 'militarist', 'fun', 'somalia', 'destabilization', 'terrorists', 'landmine', 'extinction', 'dominating', 'war', 'bombshell', 'wounded', 'lawless', 'assassination', 'fundamentalist', 'traffics', 'domination', 'blockaded', 'counterfeit', 'vulnerability', 'genocide', 'crisis', 'militarization', 'satin', 'weapons', 'combats', '7/7', 'missile', 'criminals', 'lawlessness', 'bombards', 'conflicts', 'kurd', 'assassinated', 'criminal', 'attacks', 'vulnerabilities', 'militaristic', 'aggression', 'superpower', 'counterfeits', 'forceful', 'fighters', 'infiltrator', 'military', 'warmongering', 'illegality', 'fighter', 'israelis', 'aegis', 'virus', 'hegemony', 'enemies', 'terrors', 'disobedience', 'menace', 'ballistic', 'combatants', 'wound', 'firearms', 'killers', 'nuclear', 'blocked', 'criminalizing', 'rwanda', 'explosive', 'muslims', 'division', 'drowning', 'destructor', 'insecurities', 'battle', 'terroristic', 'coup', 'separatism', 'armies', 'chemical', 'armament', 'blocks', 'warfare', 'crimean', 'assassinations', 'deterioration', 'extremism', 'grave', 'radicalism', 'explosion', 'bomber', 'threateningly', 'peril', 'caponize', 'coerce', 'bombard', 'nationalists', 'wave', 'near', 'threats', 'armour', 'infiltrate', 'islamist', 'hegemonic', 'infiltration', 'infiltrating', 'infiltrators', 'killings', 'dominantly', 'nationalistic', 'empower', 'barbarian', 'barbarians', 'illegally', 'weaponry', 'extremists', 'racists', 'afghanistan', 'disintegrates', 'crime', 'insurgents', 'separatist', 'authority', 'demise', 'rival', 'violence', 'insecure', 'criminalist', 'palestine', 'vulnerables', 'securities', 'terrorist', 'fatality', 'illicit', 'capitulated', 'weaponised', 'army', 'guevara', 'wartime', 'waves', 'alfreda', 'combated', 'fatalities', 'repressive', 'pakistan', 'insurgency', 'guerrilla', 'nazi', 'destabilize', 'terrorizes', 'hamas', 'invasions', 'airpower', 'vicious', 'deteriorate', 'radicalized', 'explosively', 'terrorize', 'disintegrated', 'hazards', 'explosions', 'combating', 'bombarded', 'threatening', 'radicalizing', 'illegals', 'killer', 'existential', 'dictator', 'attackers', 'attacker', 'ira', 'once', 'arms', 'lawbreakers', 'hussein', 'proliferation', 'kills', 'militarism', 'radicals', 'enemy', 'antipersonnel', 'evil', 'hostile', 'kurdistan', 'cybersphere', 'killzone', 'terminated', 'fighting', 'crimea', 'militaries', 'invasion', 'illegal', 'nationalization', 'fundamentalists', 'catastrophe', 'trafficking', 'bombers', 'terrorizing', 'assassin', 'death', 'casualty', 'criminalize', 'fragile', 'coercion', 'gaza', 'monsters', 'insurgencies', 'warfighter', 'hostiles', 'iraq', 'fights', 'nate', 'disaster', 'warmonger', 'lebanon', 'termination', 'coercive', 'disobedient', 'killing', 'iran', 'bombshells', 'assassinating', 'coerced', 'blitz', 'interpol', 'deaths', 'cluster', 'warfighting', 'islamic', 'bombing', 'invades', 'combat', 'bombs', 'vietnam', 'destructively', 'terrorism', 'bombardment', 'demises', 'infiltrated', 'destructed', 'forces', 'attacked', 'extinctions', 'deteriorated'}
Great, the threat_seed_lexicon_words lexicon is now all validated.

 now spell checking for threat_seed_lexicon_terms...
the misspelled words in threat_seed_lexicon_terms are: {'being radicalised': 'being radicalized'}
so the corrected ones in threat_seed_lexicon_terms were: {'nine eleven', 'wars on', 'illegal migrants', 'fuel conflicts', 'nine-eleven', 'world wars', 'serious threats', 'seven-seven', 'illegal immigrant', 'at war', 'illegal immigrants', 'war engines', 'security priorities', 'engine of war', 'new verduns', 'cogs of wars', 'invisible enemy', 'at wars', 'sea power', 'illegal migrant', 'war machines', 'war on', 'invisible enemies', 'serious threat', 'world war', 'existential threats', 'cogs of war', 'existential threat', 'prisoners of', 'war engine', 'new verdun', 'under attacks', 'fight back', 'our threat', 'toxic legacies', 'pearl harbor', 'war machine', 'being radicalized', 'a cancer', 'arm industry', 'the troubles', 'under attack', 'day slavery', 'seven seven', 'sea powers'}
Great, the threat_seed_lexicon_terms lexicon is now all validated.

 now spell checking for urgency_seed_lexicon_words...
there's actually no misspelled words found in the urgency_seed_lexicon_words.
Great, the urgency_seed_lexicon_words lexicon is now all validated.

 now spell checking for urgency_seed_lexicon_terms...
the misspelled words in urgency_seed_lexicon_terms are: {'wakeup call': 'makeup call'}
so the corrected ones in urgency_seed_lexicon_terms were: {'without delay', 'act now', 'before the election', 'cannot wait', 'any longer', 'strive for', 'supreme priorities', 'ticking clock', 'life-threatening', 'move swiftly', 'quickly moves', 'urgent priority', "can't delay", 'cannot delay', 'rapidly moves', 'swiftly moves', 'too late', 'supreme priority', 'now or never', 'end degrading', 'must not delay', 'immediate actions', "mustn't delay", 'quickly move', 'push to', 'move quickly', 'national crisis', 'makeup call', "can't wait", 'decisive actions', 'last chance', 'life threatening', 'cannot afford', 'growing crisis', 'urgent priorities', 'swiftly move', 'decisive action', 'move rapidly', 'from day one', 'breaking point', 'immediate action', 'make sure', 'on day one', 'rapidly move', 'threatening crisis', 'point of no return', 'tipping point'}
Great, the urgency_seed_lexicon_terms lexicon is now all validated.

 now spell checking for justification_of_extr_power_seed_lexicon_words...

the misspelled words in justification_of_extr_power_seed_lexicon_words are: {'stabilised': 'stabilized', 'stabilise': 'stabilize', 'detterents': 'detergents', 'detterence': 'deference', 'detterent': 'detergent', 'stabilising': 'stabilizing', 'uncooperating': 'cooperating', 'securitys': 'security'}
so the corrected ones in justification_of_extr_power_seed_lexicon_words were: {'resistances', 'surveillance', 'preventive', 'disarms', 'defend', 'enforce', 'protectorates', 'nonproliferation', 'countervail', 'toughened', 'conciliatory', 'stabilize', 'sanctioned', 'counterinsurgency', 'surveils', 'resisted', 'sovereignty', 'controlling', 'stabilizing', 'mobilise', 'abolition', 'détente', 'protectively', 'tactician', 'remove', 'prerogative', 'interdependence', 'lockdowns', 'protection', 'disarming', 'forbidding', 'deteriorating', 'abatement', 'curfews', 'detergent', 'embargo', 'cooperation', 'crackdowns', 'tactical', 'compromise', 'deterred', 'overhaul', 'detergents', 'deport', 'punitive', 'liberating', 'liberators', 'liberator', 'overdue', 'crackdown', 'lawfully', 'mobilize', 'toughening', 'sanction', 'cooperates', 'worsening', 'resistance', 'protectors', 'introduce', 'interdependent', 'decrees', 'halting', 'security', 'counterinsurgent', 'abate', 'decree', 'rescue', 'concession', 'liberated', 'counterattacks', 'liberates', 'preemptive', 'mobilizes', 'stabilized', 'sieges', 'deported', 'oversee', 'deference', 'demand', 'preventing', 'cooperate', 'preempt', 'conciliation', 'deterrence', 'controls', 'intervention', 'uncooperative', 'counterattack', 'retaliation', 'containment', 'hostage', 'forbid', 'suspensions', 'disarmed', 'suspension', 'cooperating', 'deter', 'powers', 'preventable', 'sovereigns', 'forbidden', 'surveillances', 'protects', 'interdiction', 'cooperated', 'disarmament', 'surveil', 'revenge', 'sanctioning', 'protector', 'armistice', 'mobilises', 'liberate', 'sanctions', 'tactically', 'expedite', 'intervene', 'forbids', 'liberation', 'preempted', 'prevention', 'tackle', 'preemption', 'preemptively', 'tactics', 'compels', 'curfew', 'forced', 'counteracts', 'securities', 'abolish', 'protective', 'halt', 'enforcement', 'protect', 'retaliate', 'protectorate', 'compelling', 'siege', 'homeland', 'countervailing', 'curb', 'monitor', 'prerogatives', 'sovereign', 'protections', 'prevent', 'toughen', 'lockdown', 'preventative', 'counterterrorism', 'anarchy', 'ceasefire', 'resisting', 'resist'}
Great, the justification_of_extr_power_seed_lexicon_words lexicon is now all validated.

 now spell checking for justification_of_extr_power_seed_lexicon_terms...
the misspelled words in justification_of_extr_power_seed_lexicon_terms are: {'stop brexit': 'stop credit'}
so the corrected ones in justification_of_extr_power_seed_lexicon_terms were: {'beyond politics', 'exceptional means', 'stop the boats', 'crack downs', 'without delay', 'age limits', 'cannot wait', 'age verification', 'exceptional measure', 'commander-in-chief', 'extraordinary means', 'maintain order', 'shut the borders', 'restore order', 'state of emergencies', 'ticking clock', 'breaking free', "can't accept", 'commander in chief', 'not accept', 'counter-attacks', 'tougher sentencing', 'border closures', 'shut our border', 'counter-attack', 'exceptional measures', 'break free', 'extraordinary measures', 'fast track', 'close our borders', "won't accept", 'stronger control', 'counter attacks', 'protect frontline', 'shut our borders', 'solemn duties', 'counter attack', "can't wait", 'decisive actions', 'close the borders', 'state of emergency', 'close the border', 'martial law', 'close our border', 'stop credit', 'shut the border', 'subject to', 'fight back', 'protecting people', 'decisive action', 'martial laws', 'stronger controls', 'commanders-in-chief', 'tipping point', 'crack down', 'solemn duty', 'border closure', "don't accept"}
Great, the justification_of_extr_power_seed_lexicon_terms lexicon is now all validated.

### 1c. Pluralising Root Words
By nature, any securitised word in its singular term will often still be securitised in its plural form. I desgined the following code to automatically pluralise these words to safely expand each lexicon set.

In [7]:
# this expands to pluralised terms I might have missed above
lexicon_pluraliser= inflect.engine()

def get_plural_forms_for_the_lexicon(word_set):
    pluralised_set = set(word_set)
    for word in word_set:
        # this now handles my multi-word terms by pluralising the last word if it's a noun
        if ' ' in word:
            parts_of_it= word.split()
            last_word= parts_of_it[-1]
            # I only attempt to pluralise if the last word is likely a noun (just a simple heuristic, could make it more complicated in future versions though)
            # I could even do POS tagging in future but this should still be fine. One this this doesn't catch is "war on"->"wars on" but it does do "war ons"
            if last_word and not last_word.isdigit() and not last_word.isupper() and not last_word.isdigit(): # Avoid pluralising acronyms or numbers
                plural_last_word= lexicon_pluraliser.plural(last_word)
                if plural_last_word != last_word: # here I only add if a different plural form is generated
                    pluralised_set.add(' '.join(parts_of_it[:-1] + [plural_last_word]))
        else:
            # this is the simpler case where I pluralise single words
            if not word.isdigit():
              plural_word= lexicon_pluraliser.plural(word)
              if plural_word != word:
                  pluralised_set.add(plural_word)
    return list(pluralised_set)

In [9]:
# I run that pluraliser to fetch & store all the plural words & terms for manual vetting
threat_seed_lexicon_words= get_plural_forms_for_the_lexicon(threat_seed_lexicon_words)
threat_seed_lexicon_terms= get_plural_forms_for_the_lexicon(threat_seed_lexicon_terms)
urgency_seed_lexicon_words= get_plural_forms_for_the_lexicon(urgency_seed_lexicon_words)
urgency_seed_lexicon_terms= get_plural_forms_for_the_lexicon(urgency_seed_lexicon_terms)
justification_of_extr_power_seed_lexicon_words= get_plural_forms_for_the_lexicon(justification_of_extr_power_seed_lexicon_words)
justification_of_extr_power_seed_lexicon_terms= get_plural_forms_for_the_lexicon(justification_of_extr_power_seed_lexicon_terms)

In [10]:
# 1st, all the sets are be displayed neatly
all_lexicons_flat_tiers= [
    {"Lexicon Name": "threat words", "Terms": ', '.join(sorted(list(threat_seed_lexicon_words)))},
    {"Lexicon Name": "threat terms", "Terms": ', '.join(sorted(list(threat_seed_lexicon_terms)))},
    {"Lexicon Name": "urgency words", "Terms": ', '.join(sorted(list(urgency_seed_lexicon_words)))},
    {"Lexicon Name": "urgency terms", "Terms": ', '.join(sorted(list(urgency_seed_lexicon_terms)))},
    {"Lexicon Name": "just. extr power words", "Terms": ', '.join(sorted(list(justification_of_extr_power_seed_lexicon_words)))},
    {"Lexicon Name": "just. extr power terms", "Terms": ', '.join(sorted(list(justification_of_extr_power_seed_lexicon_terms)))}
]
lexicon_df= pd.DataFrame(all_lexicons_flat_tiers)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
display(lexicon_df)

             Lexicon Name  \
0            threat words
1            threat terms
2           urgency words
3           urgency terms
4  just. extr power words
5  just. extr power terms

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Terms
0  7/7, 7/7S, 9/11, 9/11S, abm, abms, aegis, aegise, aegises, afghanistan, afghanistans, aggression, aggressions, airpower, airpowers, alqaeda, alqaedas, antipersonnel, antipersonnels, arab, arabs, arm, armament, armaments, armies, arming, armings, armories, armory, armour, armoured, armoureds, armouries, armours, armoury, arms, army, assassin, assassinate, assassinated, assassinateds, assassinates, assassinating, assassinatings, assassination, assassinations, assassins, assault, assaults, atomic, atomics, attack, attacked, attackeds, attacker, attackers, attacking, attackings, attacks, authorities, authority, ballistic, ballistics, barbarian, barbarians, battle, battles, biological, biologicals, blitz, blitzz, blitzzes, block, blockade, blockaded, blockadeds, blockades, blockading, blockadings, blocked, blockeds, blocks, bomb, bombard, bombarded, bombardeds, bombarding, bombardings, bombardment, bombardments, bombards, bombed, bombeds, bomber, bombers, bombing, bombings, bombs, bombshell, bombshells, brutal, brutals, bullet, bullets, capitulate, capitulated, capitulateds, capitulates, capitulating, capitulatings, capitulation, capitulations, casualties, casualty, catastrophe, catastrophes, catastrophic, catastrophicallies, catastrophically, catastrophics, chechnya, chechnyas, chemical, chemicals, cluster, clusters, coerce, coerced, coerceds, coerces, coercing, coercings, coercion, coercions, coercive, coercives, colonial, colonials, combat, combatant, combatants, combated, combateds, combating, combatings, combats, combatting, combattings, conflict, conflicts, counterfeit, counterfeits, coup, coups, crime, crimea, crimean, crimeans, crimeas, crimes, criminal, criminalisation, criminalisations, criminalise, criminalised, criminaliseds, criminalises, criminalization, criminalizations, criminalize, criminalized, criminalizeds, criminalizes, criminalizing, criminalizings, criminallies, criminally, criminals, crise, crises, crisis, cybersphere, cyberspheres, cyberwar, cyberwars, daesh, daeshes, death, deaths, demise, demises, destabilise, destabilises, destabilising, destabilisings, destabilization, destabilizations, destabilize, destabilized, destabilizeds, destabilizes, destabilizing, destabilizings, destructed, destructeds, destructible, destructibles, destruction, destructions, destructive, destructivelies, destructively, destructives, destructor, destructors, deteriorate, deteriorated, deteriorateds, deteriorates, deteriorating, deterioratings, deterioration, deteriorations, dictator, dictators, disaster, disasters, disease, diseases, disintegrate, disintegrated, disintegrateds, disintegrates, disintegrating, disintegratings, disintegration, disintegrations, disobedience, disobediences, disobedient, disobedients, division, divisions, dominance, dominances, dominant, dominantlies, dominantly, dominants, dominate, dominates, dominating, dominatings, domination, dominations, dominator, dominators, drowning, drownings, drug, drugs, enemies, enemy, espionage, espionages, evil, evils, existential, existentials, explosion, explosions, explosive, explosivelies, explosively, explosives, extinction, extinctions, extremism, extremisms, extremist, extremists, faction, factions, fatalities, fatality, fight, fighter, fighters, fighting, fightings, fights, firearm, firearms, fln, flns, force, forceful, forcefullies, forcefully, forcefuls, forces, fragile, fragiles, fundamentalism, fundamentalisms, fundamentalist, fundamentalists, gang, gangs, gaza, gazas, genocide, genocides, grave, graves, guerrilla, guerrillas, guevara, guevaras, gulf, gulfs, hama, hamas, hazard, hazardous, hazardouse, hazardouses, hazards, hegemonic, hegemonics, hegemonies, hegemony, hezbollah, hezbollahs, hiroshima, hiroshimas, hostile, hostiles, hussein, husseins, illegal, illegalities, illegality, illegallies, illegally, illegals, illicit, illicits, infiltrate, infiltrated, infiltrateds, infiltrates, infiltrating, infiltratings, infiltration, infiltrations, infiltrator, infiltrators, inhuman, inhumans, insecure, insecures, insecurities, insecurity, insurgencies, insurgency, insurgent, insurgents, interpol, interpols, invade, invaded, invadeds, invader, invaders, invades, invading, invadings, invasion, invasions, ira, iran, irans, iraq, iraqs, iras, islamic, islamics, islamist, islamists, israel, israeli, israelis, israelite, israelites, israels, kill, killed, killeds, killer, killers, killing, killings, kills, killswitch, killswitches, killzone, killzones, kurd, kurdish, kurdishes, kurdistan, kurdistans, kurds, landmine, landmines, lawbreaker, lawbreakers, lawless, lawlesses, lawlessness, lawlessnesses, lebanon, lebanons, libya, libyas, menace, menaces, militaries, militarisation, militarisations, militarised, militariseds, militarism, militarisms, militarist, militaristic, militaristics, militarists, militarization, militarizations, militarized, militarizeds, military, missile, missiles, monster, monsters, munition, munitions, muslim, muslims, nagasaki, nagasakis, narcotic, narcotics, nationalisation, nationalisations, nationalist, nationalistic, nationalistics, nationalists, nato, natoe, natoes, nazi, nazis, netwar, netwars, nuclear, nuclears, osce, osces, pakistan, pakistans, palestine, palestines, partisan, partisans, peril, perils, proliferating, proliferatings, proliferation, proliferations, racism, racisms, racist, racists, radical, radicalisation, radicalisations, radicalise, radicalised, radicaliseds, radicalises, radicalising, radicalisings, radicalism, radicalisms, radicalization, radicalizations, radicalize, radicalized, radicalizeds, radicalizes, radicalizing, radicalizings, radicals, repressive, repressives, rival, rivals, rogue, rogues, ruthless, ruthlesses, rwanda, rwandan, rwandans, rwandas, salw, salwar, salwars, salws, sarin, sarins, seapower, seapowers, securities, security, separatism, separatisms, separatist, separatists, shock, shocks, shortage, shortages, somalia, somalias, strike, strikes, suicide, suicides, superpower, superpowers, surveillance, surveillances, survival, survivals, syria, syrias, target, targets, terminated, terminateds, termination, terminations, terror, terrorise, terrorised, terroriseds, terrorises, terrorising, terrorisings, terrorism, terrorisms, terrorist, terroristic, terroristics, terrorists, terrorize, terrorized, terrorizeds, terrorizes, terrorizing, terrorizings, terrors, threat, threaten, threatened, threateneds, threatening, threateninglies, threateningly, threatenings, threatens, threats, traffic, trafficked, traffickeds, trafficker, traffickers, trafficking, traffickings, traffics, uprising, uprisings, vicious, viciouse, viciouses, vietnam, vietnams, violence, violences, violent, violentlies, violently, violents, virus, viruse, viruses, vulnerabilities, vulnerability, vulnerable, vulnerables, war, warfare, warfares, warfield, warfields, warfighter, warfighters, warfighting, warfightings, wargame, wargames, warhead, warheads, warmonger, warmongering, warmongerings, warmongers, warpath, warpaths, warplane, warplanes, wars, wartime, wartimes, wave, waves, weapon, weaponise, weaponised, weaponiseds, weaponises, weaponize, weaponized, weaponizeds, weaponizes, weaponries, weaponry, weapons, wmd, wmds, wound, wounded, woundeds, wounding, woundings, wounds

In [11]:
# some of the pluralised terms aren't suitable in context, so I manually remove them here to avoid clogging up the dictionaries with non-wordsl
remove_pluralised_threat_words = {"9/11S", "7/7S", "brutals", "catastrophics", "fragiles", "graves", "nine-elevens", "seven-sevens", "ruthlesses", "blitzzes", "rouges", "terminateds", "viciouses"}
remove_pluralised_threat_terms = {"new verdunes", "nine elevens", "pearl harbors", "seven sevens", "war ons", "wars ons", "a cancers", "engine of wars", "fight backs"}
threat_seed_lexicon_words = {word for word in threat_seed_lexicon_words if word not in remove_pluralised_threat_words}
threat_seed_lexicon_terms = {term for term in threat_seed_lexicon_terms if term not in remove_pluralised_threat_terms}

remove_pluralised_urgency_words = {"alarmings", "immediates", "paramounts", "unparalleleds", "unprecedenteds", "vitals", "crise", "absolutelies", "dangerouses",
                                   "urgentlies", "life-threatenings", "uncompromisinglies", "inevitables", "musts"}
remove_pluralised_urgency_terms = {"acts nows", "any longers", "can't delays", "can't waits", "cannot delays", "can't delays", "must act nows", "must not delays",
                                   "mustn't delays", "no longers", "point of no returns", "too lates", "cannot waits", "act nows", "life threatenings",
                                   "move swiftlies", "move rapidlies", "move quicklies"}
urgency_seed_lexicon_words = {word for word in urgency_seed_lexicon_words if word not in remove_pluralised_urgency_words}
urgency_seed_lexicon_terms = {term for term in urgency_seed_lexicon_terms if term not in remove_pluralised_urgency_terms}

remove_pluralised_justification_of_extr_power_words = {"compelleds"}
remove_pluralised_justification_of_extr_power_terms = {"above politic", "beyond politic", "breaking frees", "commander in chiefs", "exceptional mean", "extraordinary mean",
                                                       "maintain orders", "restore orders", "extraordinary measure", "fight backs"}
justification_of_extr_power_seed_lexicon_words = {term for term in justification_of_extr_power_seed_lexicon_words if term not in remove_pluralised_justification_of_extr_power_words}
justification_of_extr_power_seed_lexicon_terms = {term for term in justification_of_extr_power_seed_lexicon_terms if term not in remove_pluralised_justification_of_extr_power_terms}


# & quick sanity-check of the current state of the lexicons
print(f"Threat words: {threat_seed_lexicon_words}")
print(f"Threat terms: {threat_seed_lexicon_terms}")
print(f"Urgency words: {urgency_seed_lexicon_words}")
print(f"Urgency terms: {urgency_seed_lexicon_terms}")
print(f"Just. extr power words: {justification_of_extr_power_seed_lexicon_words}")
print(f"Just. extr power terms: {justification_of_extr_power_seed_lexicon_terms}")

Threat words: {'suicide', 'chemicals', 'killed', 'disintegration', 'natoes', 'gulf', 'warmongers', 'strike', 'kurdish', 'armoured', 'bombed', 'crimes', 'surveillance', 'warheads', 'wargames', 'bullet', 'brutal', 'nationalist', 'capitulating', 'casualties', 'guevaras', 'arming', 'drugs', 'combateds', 'destructible', 'faction', 'interpols', 'killeds', 'aegise', 'wars', 'traffickers', 'militarizations', 'blockade', 'dominances', 'gang', 'infiltrations', 'terrorizeds', 'biologicals', 'rivals', 'threatens', 'conflict', 'fln', 'attack', 'assault', 'illicits', 'infiltrateds', 'radicalizings', 'catastrophicallies', 'invaders', 'islamics', 'racist', 'islamists', 'violent', 'destruction', 'violently', 'militarized', 'invadeds', 'ruthless', 'trafficker', 'traffickeds', 'radicalize', 'coercing', 'nato', 'seapower', 'munitions', 'warplane', 'killzones', 'invader', 'weapon', 'landmines', 'lawlessnesses', 'target', 'destructeds', 'munition', 'hazardouses', 'existentials', 'guerrillas', 'narcotic', 'catastrophic', 'atomics', 'invading', 'chechnya', 'extremisms', 'armoury', 'criminallies', 'monster', 'attackings', 'invaded', 'combatant', 'explosives', 'destabilizing', 'lawlesses', 'assassins', 'nationalisations', 'dominantlies', 'hegemonics', 'terrorising', 'militarised', 'militaristics', 'hama', 'destructivelies', 'combatting', 'partisans', 'rwandan', 'radicalization', 'viruses', 'terror', 'bombarding', 'shortage', 'menaces', 'blockading', 'weaponiseds', 'hezbollah', 'woundings', 'terrorise', 'dominate', 'terrorisms', 'deteriorates', 'vietnams', 'criminalized', 'militarisms', 'racism', 'blockadeds', 'bombardments', 'threat', 'warhead', 'blockades', 'irans', 'terroristics', 'blockadings', 'diseases', 'israel', 'weaponizeds', 'espionages', 'nationalistics', 'armours', 'traffic', 'atomic', 'armory', 'disease', 'cyberwars', 'espionage', 'warpaths', 'fundamentalism', 'terroriseds', 'infiltrates', 'killswitch', 'dominant', 'terrorised', 'hiroshima', 'viciouse', 'catastrophically', 'dominators', 'vulnerable', 'dominations', 'hazardous', 'criminaliseds', 'hazard', '9/11', 'coups', 'colonial', 'hegemonies', 'wounding', 'threaten', 'separatists', 'bombings', 'invade', 'coercings', 'infiltratings', 'alqaeda', 'radicalizes', 'racisms', 'inhuman', 'survival', 'criminalizes', 'shocks', 'attacking', 'destructives', 'radicaliseds', 'netwar', 'criminalise', 'invadings', 'capitulate', 'trafficked', 'dominates', 'israels', 'disintegrate', 'proliferating', 'insurgent', 'osce', 'criminally', 'capitulation', 'warfares', 'destructive', 'criminalization', 'cyberwar', 'threatened', 'israeli', 'assassinate', 'nuclears', 'deteriorating', 'shock', 'biological', 'nagasaki', 'disintegrating', 'warpath', 'criminalizings', 'dominator', 'proliferatings', 'destabilized', 'israelite', 'wartimes', 'forcefully', 'explosivelies', 'targets', 'salwars', 'syria', 'dominance', 'insecurity', 'rogue', 'uprising', 'catastrophes', 'killswitches', 'disobedients', 'partisan', 'daeshes', 'drownings', 'uprisings', 'destabilizations', 'arab', 'terrorized', 'perils', 'destabilises', 'armaments', 'wounds', 'warplanes', 'libya', 'kurds', 'extremist', 'weaponise', 'narcotics', 'militarist', 'survivals', 'somalia', 'threateninglies', 'destabilization', 'terrorists', 'landmine', 'flns', 'warfields', 'extinction', 'dominating', 'assassinateds', 'war', 'kurdishes', 'colonials', 'bombshell', 'wounded', 'blockeds', 'hiroshimas', 'lawless', 'assassination', 'fundamentalist', 'separatisms', 'traffics', 'disintegratings', 'divisions', 'domination', 'blockaded', 'counterfeit', 'gazas', 'armoureds', 'threateneds', 'dominatings', 'fight', 'vulnerability', 'genocide', 'crisis', 'destabilisings', 'hazardouse', 'militarisations', 'militarization', 'warfightings', 'armouries', 'terrorisings', 'weapons', 'combats', '7/7', 'insecures', 'nationalisation', 'hezbollahs', 'missile', 'criminals', 'lawlessness', 'capitulateds', 'bombards', 'destructions', 'conflicts', 'coerces', 'kurd', 'assassinated', 'antipersonnels', 'syrias', 'criminal', 'disintegrations', 'combattings', 'attacks', 'vulnerabilities', 'salw', 'militaristic', 'aggression', 'strikes', 'coerceds', 'superpower', 'rogues', 'counterfeits', 'forceful', 'terminations', 'coercions', 'disintegrateds', 'fighters', 'infiltrator', 'military', 'forcefuls', 'warmongering', 'woundeds', 'illegality', 'natoe', 'fighter', 'israelis', 'aegis', 'virus', 'criminalisation', 'hegemony', 'bullets', 'enemies', 'terrors', 'menace', 'disobedience', 'radicalisms', 'clusters', 'ballistic', 'cyberspheres', 'combatants', 'wound', 'muslim', 'battles', 'firearms', 'killers', 'nuclear', 'blocked', 'criminalizing', 'suicides', 'rwanda', 'assassinatings', 'explosive', 'muslims', 'authorities', 'factions', 'terrorises', 'division', 'drowning', 'rwandas', 'destructor', 'deteriorateds', 'arm', 'radical', 'insecurities', 'battle', 'fundamentalisms', 'viruse', 'security', 'terroristic', 'coup', 'crise', 'separatism', 'coercives', 'warfield', 'armies', 'chemical', 'armament', 'blocks', 'warfare', 'armories', 'crimean', 'assassinations', 'deterioration', 'radicalises', 'extremism', 'grave', 'radicalism', 'explosion', 'bomber', 'threateningly', 'peril', 'coerce', 'criminalizations', 'firearm', 'bombard', 'arabs', 'netwars', 'nationalists', 'wave', 'threats', 'ballistics', 'armour', 'infiltrate', 'kurdistans', 'islamist', 'salws', 'hegemonic', 'superpowers', 'infiltration', 'chechnyas', 'surveillances', 'criminalisations', 'infiltrating', 'infiltrators', 'killings', 'dominantly', 'nationalistic', 'afghanistans', 'gulfs', 'barbarian', 'barbarians', 'illegally', 'weaponries', 'weaponry', 'racists', 'extremists', 'afghanistan', 'disintegrates', 'illegalities', 'crime', 'weaponizes', 'insurgents', 'separatist', 'israelites', 'authority', 'rival', 'demise', 'violence', 'militarisation', 'weaponises', 'insecure', 'palestine', 'vulnerables', 'securities', 'violentlies', 'illegallies', 'terrorist', 'fatality', 'capitulations', 'illicit', 'palestines', 'capitulated', 'destabilizes', 'deterioratings', 'weaponised', 'kill', 'evils', 'army', 'sarins', 'terrorizings', 'guevara', 'assassinates', 'wartime', 'destabilizings', 'radicalisings', 'radicalisations', 'fightings', 'waves', 'alqaedas', 'disasters', 'combated', 'fatalities', 'wmd', 'repressive', 'pakistan', 'dominants', 'insurgency', 'threatenings', 'guerrilla', 'weaponized', 'nazi', 'radicalised', 'destabilize', 'terrorizes', 'block', 'hamas', 'warfighters', 'invasions', 'airpower', 'bombardeds', 'criminalises', 'vicious', 'dictators', 'destabilising', 'deteriorate', 'radicalized', 'wmds', 'explosively', 'destructors', 'terrorize', 'radicalizations', 'disintegrated', 'hazards', 'explosions', 'assaults', 'combating', 'bombarded', 'iras', 'threatening', 'radicalizing', 'missiles', 'illegals', 'killer', 'existential', 'dictator', 'salwar', 'capitulates', 'aegises', 'attackers', 'armings', 'destabilise', 'attacker', 'combatings', 'destructibles', 'aggressions', 'nagasakis', 'ira', 'gangs', 'radicalizeds', 'bombardings', 'criminalised', 'arms', 'lawbreakers', 'lawbreaker', 'hussein', 'destabilizeds', 'militarizeds', 'proliferation', 'pakistans', 'militarists', 'kills', 'militarism', 'lebanons', 'radicals', 'violents', 'abms', 'abm', 'warmongerings', 'enemy', 'antipersonnel', 'repressives', 'deteriorations', 'disobediences', 'evil', 'hostile', 'kurdistan', 'forcefullies', 'cybersphere', 'iraqs', 'sarin', 'killzone', 'fighting', 'terminated', 'crimea', 'genocides', 'militaries', 'capitulatings', 'invasion', 'illegal', 'fundamentalists', 'catastrophe', 'trafficking', 'bombers', 'terrorizing', 'wargame', 'assassin', 'blitzz', 'death', 'proliferations', 'casualty', 'somalias', 'attackeds', 'criminalize', 'radicalisation', 'daesh', 'fragile', 'coercion', 'gaza', 'nazis', 'crimeans', 'monsters', 'bombeds', 'insurgencies', 'warfighter', 'hostiles', 'crises', 'drug', 'radicalise', 'iraq', 'libyas', 'husseins', 'fights', 'inhumans', 'weaponize', 'disaster', 'warmonger', 'lebanon', 'termination', 'coercive', 'disobedient', 'force', 'killing', 'rwandans', 'iran', 'bombshells', 'assassinating', 'shortages', 'coerced', 'blitz', 'interpol', 'deaths', 'cluster', 'osces', 'warfighting', 'violences', 'crimeas', 'islamic', 'bombing', 'airpowers', 'seapowers', 'invades', 'combat', 'bombs', 'vietnam', 'destructively', 'terrorism', 'traffickings', 'bombardment', 'demises', 'infiltrated', 'destructed', 'forces', 'attacked', 'militariseds', 'radicalising', 'extinctions', 'criminalizeds', 'deteriorated', 'bomb'}
Threat terms: {'seven-sevens', 'nine eleven', 'wars on', 'illegal migrants', 'fuel conflicts', 'nine-eleven', 'world wars', 'serious threats', 'nine-elevens', 'being radicaliseds', 'seven-seven', 'illegal immigrant', 'prisoners ofs', 'at war', 'the trouble', 'illegal immigrants', 'war engines', 'security priorities', 'engine of war', 'new verduns', 'cogs of wars', 'invisible enemy', 'at wars', 'sea power', 'illegal migrant', 'war machines', 'war on', 'being radicalised', 'invisible enemies', 'serious threat', 'world war', 'existential threats', 'cogs of war', 'existential threat', 'prisoners of', 'war engine', 'fuel conflict', 'our threats', 'security priority', 'new verdun', 'under attacks', 'fight back', 'our threat', 'toxic legacies', 'pearl harbor', 'war machine', 'arm industries', 'a cancer', 'arm industry', 'the troubles', 'day slaveries', 'under attack', 'day slavery', 'seven seven', 'sea powers', 'toxic legacy'}
Urgency words: {'demand', 'swifts', 'scarces', 'armageddon', 'mounting', 'worsenings', 'overdues', 'tackle', 'escalation', 'immediate', 'crisis', 'urgents', 'inevitability', 'ensure', 'overdue', 'mountings', 'critical', 'collapseds', 'scarcelies', 'overrun', 'imminent', 'imminently', 'emergencies', 'escalates', 'worsening', 'immediately', 'ensures', 'escalating', 'overruns', 'reacts', 'urgently', 'scarcely', 'swift', 'demands', 'criticals', 'paramount', 'crises', 'escalate', 'escalations', 'collapse', 'react', 'scarce', 'collapsing', 'tackles', 'spirallings', 'urgent', 'scarcities', 'reaction', 'unprecedented', 'imminentlies', 'reactions', 'irreversibles', 'collapses', 'inevitable', 'armageddons', 'collapsed', 'unparalleled', 'imminents', 'escalatings', 'inevitabilities', 'collapsings', 'emergency', 'scarcity', 'irreversible', 'spiralling', 'immediatelies'}
Urgency terms: {'ticking clocks', 'without delay', 'act now', 'before the election', 'tipping points', 'cannot wait', 'any longer', 'supreme priorities', 'strive for', 'ticking clock', 'life-threatening', 'move swiftly', 'without delays', 'quickly moves', 'urgent priority', "can't delay", 'rapidly moves', 'cannot delay', 'swiftly moves', 'too late', 'supreme priority', 'life-threatenings', 'now or never', 'end degrading', 'threatening crises', 'must not delay', 'immediate actions', 'national crises', "mustn't delay", 'quickly move', 'breaking points', 'push to', 'move quickly', 'national crisis', 'make sures', "can't wait", 'decisive actions', 'from day ones', 'wakeup calls', 'end degradings', 'last chance', 'life threatening', 'cannot afford', 'growing crisis', 'urgent priorities', 'growing crises', 'move rapidly', 'before the elections', 'swiftly move', 'decisive action', 'push toes', 'from day one', 'last chances', 'breaking point', 'make sure', 'now or nevers', 'wakeup call', 'immediate action', 'on day one', 'rapidly move', 'strive fors', 'point of no return', 'tipping point', 'threatening crisis', 'on day ones', 'cannot affords'}
Just. extr power words: {'resistances', 'stabilised', 'abolitions', 'stabilisings', 'countervailings', 'preventive', 'surveillance', 'disarms', 'disarmeds', 'defend', 'enforce', 'protectorates', 'nonproliferation', 'countervail', 'toughened', 'tacticals', 'detterences', 'conciliatory', 'forbiddings', 'oversees', 'sanctioned', 'counterinsurgency', 'surveils', 'resists', 'resisted', 'preempts', 'sovereignty', 'controlling', 'mobilise', 'liberations', 'resisting', 'abolition', 'détente', 'liberatings', 'demands', 'tougheneds', 'protectively', 'stabilise', 'tactician', 'remove', 'deterreds', 'prerogative', 'interdependence', 'introduces', 'lockdowns', 'enforces', 'prevents', 'protection', 'disarming', 'tactic', 'haltings', 'forbidding', 'deteriorating', 'abatement', 'curfews', 'interdependents', 'embargo', 'sanctioneds', 'cooperation', 'crackdowns', 'tactical', 'stabilises', 'compromise', 'deterred', 'overhaul', 'rescues', 'deport', 'forceds', 'punitive', 'retaliates', 'liberating', 'disarmaments', 'detterents', 'preventives', 'liberators', 'liberator', 'preventatives', 'disarmings', 'overdue', 'conciliations', 'crackdown', 'lawfully', 'overhauls', 'uncooperatings', 'defends', 'mobilize', 'preemptions', 'protectives', 'toughening', 'ceasefires', 'sanction', 'cooperates', 'worsening', 'resisteds', 'resistance', 'protectors', 'interdictions', 'introduce', 'interdependent', 'decrees', 'halting', 'cooperations', 'preemptives', 'security', 'counterinsurgent', 'abate', 'decree', 'rescue', 'homelands', 'tackles', 'concession', 'liberated', 'counterattacks', 'halts', 'liberates', 'preemptive', 'mobilizes', 'containments', 'sieges', 'deported', 'revenges', 'oversee', 'detterence', 'interventions', 'demand', 'intervenes', 'counteract', 'preventing', 'forbiddens', 'deterrences', 'compellings', 'conciliatories', 'compromises', 'cooperate', 'preempt', 'conciliation', 'stabiliseds', 'removes', 'deterrence', 'detterent', 'preventings', 'controls', 'intervention', 'uncooperative', 'embargoes', 'counterattack', 'tacticallies', 'retaliation', 'abolishes', 'containment', 'anarchies', 'détentes', 'deports', 'preventions', 'hostage', 'resistings', 'forbid', 'countervails', 'suspensions', 'disarmed', 'suspension', 'stabilising', 'cooperating', 'deter', 'powers', 'preventable', 'sovereigns', 'punitives', 'forbidden', 'surveillances', 'hostages', 'protects', 'armistices', 'retaliations', 'interdiction', 'cooperated', 'disarmament', 'surveil', 'revenge', 'uncooperating', 'sovereignties', 'toughenings', 'sanctionings', 'sanctioning', 'protector', 'armistice', 'mobilises', 'liberate', 'sanctions', 'tactically', 'control', 'expedite', 'intervene', 'cooperateds', 'monitors', 'forbids', 'liberation', 'expedites', 'preemptivelies', 'tacticians', 'preempted', 'prevention', 'compel', 'worsenings', 'overdues', 'tackle', 'preemption', 'preemptively', 'tactics', 'interdependences', 'compels', 'lawfullies', 'curfew', 'forced', 'power', 'counterinsurgencies', 'counteracts', 'securities', 'abates', 'abolish', 'concessions', 'disarm', 'protective', 'halt', 'enforcement', 'protect', 'retaliate', 'abatements', 'protectorate', 'counterterrorisms', 'deters', 'compelling', 'siege', 'homeland', 'securitys', 'countervailing', 'curb', 'monitor', 'cooperatings', 'prerogatives', 'sovereign', 'curbs', 'protections', 'deterioratings', 'liberateds', 'preventables', 'controllings', 'prevent', 'nonproliferations', 'toughen', 'counterinsurgents', 'lockdown', 'enforcements', 'preventative', 'counterterrorism', 'anarchy', 'protectivelies', 'preempteds', 'ceasefire', 'toughens', 'uncooperatives', 'resist', 'deporteds'}
Just. extr power terms: {'age verifications', 'ticking clocks', 'exceptional measure', 'breaking free', "can't accept", 'counter-attacks', 'counter-attack', 'exceptional measures', 'subject toes', "can't waits", 'counter attacks', 'protect frontline', 'counter attack', 'decisive actions', 'shut the border', 'protecting people', 'stop the boat', 'commanders-in-chief', 'tipping point', 'shut the borders', 'crack down', 'commanderss-in-chief', 'without delay', 'crack downs', 'fast tracks', 'age limits', 'cannot wait', 'maintain order', 'state of emergencies', 'ticking clock', 'tougher sentencing', 'shut our border', "won't accepts", 'age limit', 'close our borders', "won't accept", 'not accepts', 'break frees', 'close our border', 'protect frontlines', 'subject to', 'fight back', 'stronger controls', 'cannot waits', 'protecting peoples', 'state of emergency', 'beyond politics', 'exceptional means', 'stop the boats', 'tipping points', 'commander-in-chief', 'extraordinary means', 'without delays', 'not accept', 'border closures', 'break free', "can't accepts", 'fast track', 'stronger control', "can't wait", 'stop brexits', 'tougher sentencings', 'martial laws', "don't accepts", 'solemn duty', 'age verification', 'restore order', 'commander in chief', 'stop brexit', 'extraordinary measures', 'shut our borders', 'solemn duties', 'close the borders', 'close the border', 'martial law', 'decisive action', 'border closure', "don't accept"}

### 1d. Categorising Terms
Now these terms must be categorised based on contextual intensity.
1. Core signals unambiguously enact securitisation.
2. Secondary signals itensify/legitimise it
3. Contextual signals ("contingent lexicon" in literature) gain securitising power in context due to their specific socio-cultural resonance or historical weight.

These align with my research:

* Frame semantics (frame-evoking vs frame-supporting elements)
* Speech act theory (illocutionary force [intended action] vs perlocutionary reinforcement [effect from utterance])
* Discourse analysis: core claim vs justificatory scaffolding

I use these 3 signal types will to weight securitisation regression. They also allow me room for more in-depth analysis, but you can check out my paper for more details on that.

Grading between categories varies between dimensions as each one has distinctive features; threat establishes existential danger, urgency compresses time & pushes urgency, and justifying extyraordinary measures legitimises suspending normal politics.

**Threat**

| Signal Tier | Definition / Criteria | Validated Examples from Sources |
| :--- | :--- | :--- |
| **Core** | The vocabulary of survival: Words explicitly denoting the end of existence or presence of a fundamental danger. **Test:** Does this word frame something as a serious or existential threat without needing extra context? | "existential threat", "survival", "war" (generic lexicon), "peril", "extinction". |
| **Secondary** | The vocabularly of hostility: words that help to create a "Self-Other" dichotomy, assigning agency and malevolence to the threat to make it "actorised". **Test:** Does this word describe the threat as distinctively evil or aggressive? | "vicious", "brutal", "Invisible enemy", "infiltrating", "rogue", "barbarians", "counter-attack". |
| **Contextual** | The vocabularly of vulnerability. "Thick signifiers" that trigger specific cultural traumas or name the specific object at risk. **Test:** Is this word a historical event or a specific policy topic (e.g., health, migration) being framed as dangerous? | "pearl harbor", "the blitz", "9/11" (historical analogies); "virus", "migrant", "waves" (metaphor). |

**Urgency**

| Signal Tier | Definition / Criteria | Validated Examples from Sources |
| :--- | :--- | :--- |
| **Core** | The vocabulary of immediacy. Temporal markers that explicitly collapse the timeframe for decision-making, signalling that the opportunity to act is vanishing. **Test:** does this word assert that action must happen *now* or that time has run out? | "urgent", "immediate", "point of no return", "crisis", "supreme priority", "ticking clock". |
| **Secondary** | The vocabulary of priority and escalation. Words that elevate an issue above others, emphasising that something must be done soon to avoid a disaster, or that a situation is worsening. **Test:** does this word claim the issue is exceptional, deteriorating, or cannot be deferred? | "unprecedented", "vital", "paramount", "Inevitable". |
| **Contextual** | The vocabulary of commitment and insistence. Language expressing determination or resolve to act, which implies urgency through intensity of commitment without explicitly invoking time pressure or crisis. **Test:** does this word signal strong intent to act without specifying a timeframe? | "ensure", "strive to", "push for". |

**Justification of Extr. Power**

| Signal Tier | Definition / Criteria | Validated Examples from Sources |
| :--- | :--- | :--- |
| **Core** | The vocabulary of exception. Words that explicitly signal the suspension of the normal legal/political order. **Test:** Does this word legally or conceptually denote a break from the norm? | "state of emergency", "exceptional measures", "martial law", "breaking free", "suspension". |
| **Secondary** | Words that invoke institutional legitimacy, moral obligation, or the mandate to act decisively. **Test:** Does this word assert the power or responsibility to act beyond normal deliberation? | "commander in chief", "solemn duty", "order", "mobilise", "must", "compelled". |
| **Contextual** | The vocabulary of tools. Specific policy instruments that become "extraordinary" only when linked to the threat. In normal times, these might be administrative; in security times, they are survival tools. **Test:** Is this a specific policy tool (e.g., border closure, censorship)? | "lockdown", "surveillance", "quarantine", "border closure", "sanctions". |

In [12]:
# I now use dicts to create a mapping of words to signals
# Core signals should never really change, but the other dimensions will grow as pre-established lexicons and SBERT are utilised

threat_words_core_signals = {"survival", "survivals", "security", "securities", "threat", "peril", "perils", "extinction", "extinctions", "war", "wars",
                             "catastrophe", "catastrophic", "catastrophes", "death", "deaths", "fatalities", "fatality", "terminated", "termination",
                             "terminations", "wound", "wounds", "monster", "monsters", "threat", "threats", "invading", "invadings", "invasion", "invasions",
                             "attack", "attacks", "drowning", "drownings", "extremisms", "extremist", "extremists", "extremism"}
threat_terms_core_signals = {"existential threat", "existential threats", "serious threat", "serious threats", "war machine",
                             "war machines", "war engines", "war engine", "engine of war", "cogs of wars", "cogs of war" , "fight back"}

threat_words_secondary_signals = {"terrorist", "terrorists", "enemy", "enemies", "hostile", "hostiles", "vicious", "brutal",
                                  "infiltrating", "infiltration", "infiltrations", "infiltratings", "ruthless",  "counterfeit", "counterfeits", "rouge",
                                  "fragile", "vulnerable", "vulnerables", "vulnerability", "vulnerabilities", "demise", "demises", "erasure", "erasures",
                                  "espionage", "espionages", "barbarians", "barbarian", "illegal", "grave", "menace", "menaces",}
threat_terms_secondary_signals = {"rouge states", "rouge state", "under attack", "invisible enemy", "invisible enemies",}

threat_words_contextual_signals = {"9/11", "nine-eleven", "7/7", "seven-seven", "blitz", "blitzes", "illegals", "graves",
                                   "waves", "wave", "virus", "viruses", "rwanda", "rwandan"}
threat_terms_contextual_signals = {"nine eleven", "seven seven", "new verdun", "new verduns", "pearl harbor", "world war", "world wars", "at war", "war on",
                                   "wars on", "at wars", "under attacks", "a cancer", "sea powers", "sea power", "illegal immigrant", "illegal immigrants", "illegal migrant", "illegal migrants"}


urgency_words_core_signals = {"urgent", "urgents", "immediate", "crisis", "crises", "life-threatening", "unparalleled", "unprecedented"}
urgency_terms_core_signals = {"point of no return", "too late", "supreme priority", "supreme priorities", "urgent priority", "urgent priorities",
                              "life threatening", "act now", "must act now"}

urgency_words_secondary_signals = {"alarming", "vital", "paramount", "uncompromisingly", "urgently", "absolutely", "dangerous", "must", "deter", "deters",
                                   "prevent", "prevents", "react", "reacts", "reaction", "reactions"}
urgency_terms_secondary_signals = {"can't wait", "cannot wait", "can't delay", "cannot delay", "must not delay", "mustn't delay", "decisive action", "decisive actions",
                                   "immediate action",  "immediate actions",}

urgency_words_contextual_signals = {"inevitabilities", "inevitability", "inevitable", }
urgency_terms_contextual_signals = {"any longer", "no longer", "move quickly", "quickly move", "quickly moves", "swiftly move", "move swiftly", "swiftly moves",
                                    "rapidly move", "move rapidly", "rapidly moves", "before the election", "rapid production", "before the elections",
                                    "rapid productions", "ticking clock", "ticking clocks", }


justification_of_extr_power_words_core_signals = {"siege", "sieges", "curfew", "curfews", "counter-attack", "counter-attacks", "counterattacks", "counterattack"}
justification_of_extr_power_terms_core_signals = {"martial law", "martial laws", "state of emergency", "state of emergencies", "exceptional measures", "exceptional measure", "extraordinary measures",
                                                  "counter attack", "counter attacks", "exceptional means", "extraordinary means", "breaking free", "restore order", "fight back",}

justification_of_extr_power_words_secondary_signals = {"sovereign", "sovereigns", "prerogative", "prerogatives", "decree", "decrees", "protect", "protects",
                                                       "compelled", "commanders-in-chief", "commander-in-chief"}
justification_of_extr_power_terms_secondary_signals = {"commander in chief", "highest duty", "highest duties", "above politics", "beyond politics", "maintain order", "solemn duty", "solemn duties"}

justification_of_extr_power_words_contextual_signals = {"lockdown", "lockdowns", "mobilise", "mobilises", "mobilize", "mobilizes", "order", "orders",
                                                        "suspension", "suspensions", "surveillance", "surveillances", "sanction", "sanctions", "surveils", "surveil"}
justification_of_extr_power_terms_contextual_signals = {"close the border", "shut the border", "shut the borders", "border closure", "shut our borders", "border closures",
                                                        "close the borders", "shut our border", "close our border", "close our borders"}

# Now I filter out all words not present in the original set

# Threat words & term signal categories are filtered against threat_seed_lexicon_words
threat_words_core_signals= {word for word in threat_words_core_signals if word in threat_seed_lexicon_words}
threat_words_secondary_signals= {word for word in threat_words_secondary_signals if word in threat_seed_lexicon_words}
threat_words_contextual_signals= {word for word in threat_words_contextual_signals if word in threat_seed_lexicon_words}

threat_terms_core_signals= {term for term in threat_terms_core_signals if term in threat_seed_lexicon_terms}
threat_terms_secondary_signals= {term for term in threat_terms_secondary_signals if term in threat_seed_lexicon_terms}
threat_terms_contextual_signals= {term for term in threat_terms_contextual_signals if term in threat_seed_lexicon_terms}

# Urgency words & terms signal categories are filtered against urgency_seed_lexicon_words
urgency_words_core_signals= {word for word in urgency_words_core_signals if word in urgency_seed_lexicon_words}
urgency_words_secondary_signals= {word for word in urgency_words_secondary_signals if word in urgency_seed_lexicon_words}
urgency_words_contextual_signals= {word for word in urgency_words_contextual_signals if word in urgency_seed_lexicon_words}

urgency_terms_core_signals= {term for term in urgency_terms_core_signals if term in urgency_seed_lexicon_terms}
urgency_terms_secondary_signals= {term for term in urgency_terms_secondary_signals if term in urgency_seed_lexicon_terms}
urgency_terms_contextual_signals= {term for term in urgency_terms_contextual_signals if term in urgency_seed_lexicon_terms}

# Justification of Extr. Power words & terms signal categories are filtered against justification_of_extr_power_seed_lexicon_words
justification_of_extr_power_words_core_signals= {word for word in justification_of_extr_power_words_core_signals if word in justification_of_extr_power_seed_lexicon_words}
justification_of_extr_power_words_secondary_signals= {word for word in justification_of_extr_power_words_secondary_signals if word in justification_of_extr_power_seed_lexicon_words}
justification_of_extr_power_words_contextual_signals= {word for word in justification_of_extr_power_words_contextual_signals if word in justification_of_extr_power_seed_lexicon_words}

justification_of_extr_power_terms_core_signals= {term for term in justification_of_extr_power_terms_core_signals if term in justification_of_extr_power_seed_lexicon_terms}
justification_of_extr_power_terms_secondary_signals= {term for term in justification_of_extr_power_terms_secondary_signals if term in justification_of_extr_power_seed_lexicon_terms}
justification_of_extr_power_terms_contextual_signals= {term for term in justification_of_extr_power_terms_contextual_signals if term in justification_of_extr_power_seed_lexicon_terms}

In [13]:
# now using the categorisations above, I use this function to set them in their corresponding class
def categorise_and_report_lexicon(lexicon_set, core_signals, secondary_signals, contextual_signals, lexicon_name):
    categorised_lexicon= {}
    for term in lexicon_set:
        if term in core_signals:
            categorised_lexicon[term]= "core"
        elif term in secondary_signals:
            categorised_lexicon[term]= "secondary"
        elif term in contextual_signals:
            categorised_lexicon[term]= "contextual"
        else:
            categorised_lexicon[term]= "n/a"

    # I highlight any ones I could've missed here
    invalid_lex_terms= [term for term, signal_type in categorised_lexicon.items() if signal_type == 'n/a']
    if invalid_lex_terms:
        print(f"oops, in {lexicon_name} I forgot to assign a signal to these terms: {invalid_lex_terms}")
    else:
        print(f"All good in {lexicon_name}, I've assigned each term a signal category")
    return categorised_lexicon

# now I categorise threat words & terms
threat_seed_lexicon_words_signal_categories= categorise_and_report_lexicon(threat_seed_lexicon_words, threat_words_core_signals, threat_words_secondary_signals, threat_words_contextual_signals, "threat words")
threat_seed_lexicon_terms_signal_categories= categorise_and_report_lexicon(threat_seed_lexicon_terms, threat_terms_core_signals, threat_terms_secondary_signals, threat_terms_contextual_signals, "threat terms")

# ... & urgency ones
urgency_seed_lexicon_words_signal_categories= categorise_and_report_lexicon(urgency_seed_lexicon_words, urgency_words_core_signals, urgency_words_secondary_signals, urgency_words_contextual_signals, "urgency words")
urgency_seed_lexicon_terms_signal_categories= categorise_and_report_lexicon(urgency_seed_lexicon_terms, urgency_terms_core_signals, urgency_terms_secondary_signals, urgency_terms_contextual_signals, "urgency terms")

# & finally justification ones too
justification_of_extr_power_seed_lexicon_words_signal_categories= categorise_and_report_lexicon(justification_of_extr_power_seed_lexicon_words, justification_of_extr_power_words_core_signals, justification_of_extr_power_words_secondary_signals, justification_of_extr_power_words_contextual_signals, "justification words")
justification_of_extr_power_seed_lexicon_terms_signal_categories= categorise_and_report_lexicon(justification_of_extr_power_seed_lexicon_terms, justification_of_extr_power_terms_core_signals, justification_of_extr_power_terms_secondary_signals, justification_of_extr_power_terms_contextual_signals, "justification terms")

oops, in threat words I forgot to assign a signal to these terms: ['suicide', 'chemicals', 'killed', 'disintegration', 'natoes', 'gulf', 'warmongers', 'strike', 'kurdish', 'armoured', 'bombed', 'crimes', 'surveillance', 'warheads', 'wargames', 'bullet', 'nationalist', 'capitulating', 'casualties', 'guevaras', 'arming', 'drugs', 'combateds', 'destructible', 'faction', 'interpols', 'killeds', 'aegise', 'traffickers', 'militarizations', 'blockade', 'dominances', 'gang', 'terrorizeds', 'biologicals', 'rivals', 'threatens', 'conflict', 'fln', 'assault', 'illicits', 'infiltrateds', 'radicalizings', 'catastrophicallies', 'invaders', 'islamics', 'racist', 'islamists', 'violent', 'destruction', 'violently', 'militarized', 'invadeds', 'trafficker', 'traffickeds', 'radicalize', 'coercing', 'nato', 'seapower', 'munitions', 'warplane', 'killzones', 'invader', 'weapon', 'landmines', 'lawlessnesses', 'target', 'destructeds', 'munition', 'hazardouses', 'existentials', 'guerrillas', 'narcotic', 'atomics', 'chechnya', 'armoury', 'criminallies', 'attackings', 'invaded', 'combatant', 'explosives', 'destabilizing', 'lawlesses', 'assassins', 'nationalisations', 'dominantlies', 'hegemonics', 'terrorising', 'militarised', 'militaristics', 'hama', 'destructivelies', 'combatting', 'partisans', 'radicalization', 'terror', 'bombarding', 'shortage', 'blockading', 'weaponiseds', 'hezbollah', 'woundings', 'terrorise', 'dominate', 'terrorisms', 'deteriorates', 'vietnams', 'criminalized', 'militarisms', 'racism', 'blockadeds', 'bombardments', 'warhead', 'blockades', 'irans', 'terroristics', 'blockadings', 'diseases', 'israel', 'weaponizeds', 'nationalistics', 'armours', 'traffic', 'atomic', 'armory', 'disease', 'cyberwars', 'warpaths', 'fundamentalism', 'terroriseds', 'infiltrates', 'killswitch', 'dominant', 'terrorised', 'hiroshima', 'viciouse', 'catastrophically', 'dominators', 'dominations', 'hazardous', 'criminaliseds', 'hazard', 'coups', 'colonial', 'hegemonies', 'wounding', 'threaten', 'separatists', 'bombings', 'invade', 'coercings', 'alqaeda', 'radicalizes', 'racisms', 'inhuman', 'criminalizes', 'shocks', 'attacking', 'destructives', 'radicaliseds', 'netwar', 'criminalise', 'capitulate', 'trafficked', 'dominates', 'israels', 'disintegrate', 'proliferating', 'insurgent', 'osce', 'criminally', 'capitulation', 'warfares', 'destructive', 'criminalization', 'cyberwar', 'threatened', 'israeli', 'assassinate', 'nuclears', 'deteriorating', 'shock', 'biological', 'nagasaki', 'disintegrating', 'warpath', 'criminalizings', 'dominator', 'proliferatings', 'destabilized', 'israelite', 'wartimes', 'forcefully', 'explosivelies', 'targets', 'salwars', 'syria', 'dominance', 'insecurity', 'rogue', 'uprising', 'killswitches', 'disobedients', 'partisan', 'daeshes', 'uprisings', 'destabilizations', 'arab', 'terrorized', 'destabilises', 'armaments', 'warplanes', 'libya', 'kurds', 'weaponise', 'narcotics', 'militarist', 'somalia', 'threateninglies', 'destabilization', 'landmine', 'flns', 'warfields', 'dominating', 'assassinateds', 'kurdishes', 'colonials', 'bombshell', 'wounded', 'blockeds', 'hiroshimas', 'lawless', 'assassination', 'fundamentalist', 'separatisms', 'traffics', 'disintegratings', 'divisions', 'domination', 'blockaded', 'gazas', 'armoureds', 'threateneds', 'dominatings', 'fight', 'genocide', 'crisis', 'destabilisings', 'hazardouse', 'militarisations', 'militarization', 'warfightings', 'armouries', 'terrorisings', 'weapons', 'combats', 'insecures', 'nationalisation', 'hezbollahs', 'missile', 'criminals', 'lawlessness', 'capitulateds', 'bombards', 'destructions', 'conflicts', 'coerces', 'kurd', 'assassinated', 'antipersonnels', 'syrias', 'criminal', 'disintegrations', 'combattings', 'salw', 'militaristic', 'aggression', 'strikes', 'coerceds', 'superpower', 'rogues', 'forceful', 'coercions', 'disintegrateds', 'fighters', 'infiltrator', 'military', 'forcefuls', 'warmongering', 'woundeds', 'illegality', 'natoe', 'fighter', 'israelis', 'aegis', 'criminalisation', 'hegemony', 'bullets', 'terrors', 'disobedience', 'radicalisms', 'clusters', 'ballistic', 'cyberspheres', 'combatants', 'muslim', 'battles', 'firearms', 'killers', 'nuclear', 'blocked', 'criminalizing', 'suicides', 'assassinatings', 'explosive', 'muslims', 'authorities', 'factions', 'terrorises', 'division', 'rwandas', 'destructor', 'deteriorateds', 'arm', 'radical', 'insecurities', 'battle', 'fundamentalisms', 'viruse', 'terroristic', 'coup', 'crise', 'separatism', 'coercives', 'warfield', 'armies', 'chemical', 'armament', 'blocks', 'warfare', 'armories', 'crimean', 'assassinations', 'deterioration', 'radicalises', 'radicalism', 'explosion', 'bomber', 'threateningly', 'coerce', 'criminalizations', 'firearm', 'bombard', 'arabs', 'netwars', 'nationalists', 'ballistics', 'armour', 'infiltrate', 'kurdistans', 'islamist', 'salws', 'hegemonic', 'superpowers', 'chechnyas', 'surveillances', 'criminalisations', 'infiltrators', 'killings', 'dominantly', 'nationalistic', 'afghanistans', 'gulfs', 'illegally', 'weaponries', 'weaponry', 'racists', 'afghanistan', 'disintegrates', 'illegalities', 'crime', 'weaponizes', 'insurgents', 'separatist', 'israelites', 'authority', 'rival', 'violence', 'militarisation', 'weaponises', 'insecure', 'palestine', 'violentlies', 'illegallies', 'capitulations', 'illicit', 'palestines', 'capitulated', 'destabilizes', 'deterioratings', 'weaponised', 'kill', 'evils', 'army', 'sarins', 'terrorizings', 'guevara', 'assassinates', 'wartime', 'destabilizings', 'radicalisings', 'radicalisations', 'fightings', 'alqaedas', 'disasters', 'combated', 'wmd', 'repressive', 'pakistan', 'dominants', 'insurgency', 'threatenings', 'guerrilla', 'weaponized', 'nazi', 'radicalised', 'destabilize', 'terrorizes', 'block', 'hamas', 'warfighters', 'airpower', 'bombardeds', 'criminalises', 'dictators', 'destabilising', 'deteriorate', 'radicalized', 'wmds', 'explosively', 'destructors', 'terrorize', 'radicalizations', 'disintegrated', 'hazards', 'explosions', 'assaults', 'combating', 'bombarded', 'iras', 'threatening', 'radicalizing', 'missiles', 'killer', 'existential', 'dictator', 'salwar', 'capitulates', 'aegises', 'attackers', 'armings', 'destabilise', 'attacker', 'combatings', 'destructibles', 'aggressions', 'nagasakis', 'ira', 'gangs', 'radicalizeds', 'bombardings', 'criminalised', 'arms', 'lawbreakers', 'lawbreaker', 'hussein', 'destabilizeds', 'militarizeds', 'proliferation', 'pakistans', 'militarists', 'kills', 'militarism', 'lebanons', 'radicals', 'violents', 'abms', 'abm', 'warmongerings', 'antipersonnel', 'repressives', 'deteriorations', 'disobediences', 'evil', 'kurdistan', 'forcefullies', 'cybersphere', 'iraqs', 'sarin', 'killzone', 'fighting', 'crimea', 'genocides', 'militaries', 'capitulatings', 'fundamentalists', 'trafficking', 'bombers', 'terrorizing', 'wargame', 'assassin', 'blitzz', 'proliferations', 'casualty', 'somalias', 'attackeds', 'criminalize', 'radicalisation', 'daesh', 'coercion', 'gaza', 'nazis', 'crimeans', 'bombeds', 'insurgencies', 'warfighter', 'crises', 'drug', 'radicalise', 'iraq', 'libyas', 'husseins', 'fights', 'inhumans', 'weaponize', 'disaster', 'warmonger', 'lebanon', 'coercive', 'disobedient', 'force', 'killing', 'rwandans', 'iran', 'bombshells', 'assassinating', 'shortages', 'coerced', 'interpol', 'cluster', 'osces', 'warfighting', 'violences', 'crimeas', 'islamic', 'bombing', 'airpowers', 'seapowers', 'invades', 'combat', 'bombs', 'vietnam', 'destructively', 'terrorism', 'traffickings', 'bombardment', 'infiltrated', 'destructed', 'forces', 'attacked', 'militariseds', 'radicalising', 'criminalizeds', 'deteriorated', 'bomb']
oops, in threat terms I forgot to assign a signal to these terms: ['seven-sevens', 'fuel conflicts', 'nine-eleven', 'nine-elevens', 'being radicaliseds', 'seven-seven', 'prisoners ofs', 'the trouble', 'security priorities', 'being radicalised', 'prisoners of', 'fuel conflict', 'our threats', 'security priority', 'our threat', 'toxic legacies', 'arm industries', 'arm industry', 'the troubles', 'day slaveries', 'day slavery', 'toxic legacy']
oops, in urgency words I forgot to assign a signal to these terms: ['demand', 'swifts', 'scarces', 'armageddon', 'mounting', 'worsenings', 'overdues', 'tackle', 'escalation', 'ensure', 'overdue', 'mountings', 'critical', 'collapseds', 'scarcelies', 'overrun', 'imminent', 'imminently', 'emergencies', 'escalates', 'worsening', 'immediately', 'ensures', 'escalating', 'overruns', 'scarcely', 'swift', 'demands', 'criticals', 'escalate', 'escalations', 'collapse', 'scarce', 'collapsing', 'tackles', 'spirallings', 'scarcities', 'imminentlies', 'irreversibles', 'collapses', 'armageddons', 'collapsed', 'imminents', 'escalatings', 'collapsings', 'emergency', 'scarcity', 'irreversible', 'spiralling', 'immediatelies']
oops, in urgency terms I forgot to assign a signal to these terms: ['without delay', 'tipping points', 'strive for', 'life-threatening', 'without delays', 'life-threatenings', 'now or never', 'end degrading', 'threatening crises', 'national crises', 'breaking points', 'push to', 'national crisis', 'make sures', 'from day ones', 'wakeup calls', 'end degradings', 'last chance', 'cannot afford', 'growing crisis', 'growing crises', 'push toes', 'from day one', 'last chances', 'breaking point', 'make sure', 'now or nevers', 'wakeup call', 'on day one', 'strive fors', 'tipping point', 'threatening crisis', 'on day ones', 'cannot affords']
oops, in justification words I forgot to assign a signal to these terms: ['resistances', 'stabilised', 'abolitions', 'stabilisings', 'countervailings', 'preventive', 'disarms', 'disarmeds', 'defend', 'enforce', 'protectorates', 'nonproliferation', 'countervail', 'toughened', 'tacticals', 'detterences', 'conciliatory', 'forbiddings', 'oversees', 'sanctioned', 'counterinsurgency', 'resists', 'resisted', 'preempts', 'sovereignty', 'controlling', 'liberations', 'resisting', 'abolition', 'détente', 'liberatings', 'demands', 'tougheneds', 'protectively', 'stabilise', 'tactician', 'remove', 'deterreds', 'interdependence', 'introduces', 'enforces', 'prevents', 'protection', 'disarming', 'tactic', 'haltings', 'forbidding', 'deteriorating', 'abatement', 'interdependents', 'embargo', 'sanctioneds', 'cooperation', 'crackdowns', 'tactical', 'stabilises', 'compromise', 'deterred', 'overhaul', 'rescues', 'deport', 'forceds', 'punitive', 'retaliates', 'liberating', 'disarmaments', 'detterents', 'preventives', 'liberators', 'liberator', 'preventatives', 'disarmings', 'overdue', 'conciliations', 'crackdown', 'lawfully', 'overhauls', 'uncooperatings', 'defends', 'preemptions', 'protectives', 'toughening', 'ceasefires', 'cooperates', 'worsening', 'resisteds', 'resistance', 'protectors', 'interdictions', 'introduce', 'interdependent', 'halting', 'cooperations', 'preemptives', 'security', 'counterinsurgent', 'abate', 'rescue', 'homelands', 'tackles', 'concession', 'liberated', 'halts', 'liberates', 'preemptive', 'containments', 'deported', 'revenges', 'oversee', 'detterence', 'interventions', 'demand', 'intervenes', 'counteract', 'preventing', 'forbiddens', 'deterrences', 'compellings', 'conciliatories', 'compromises', 'cooperate', 'preempt', 'conciliation', 'stabiliseds', 'removes', 'deterrence', 'detterent', 'preventings', 'controls', 'intervention', 'uncooperative', 'embargoes', 'tacticallies', 'retaliation', 'abolishes', 'containment', 'anarchies', 'détentes', 'deports', 'preventions', 'hostage', 'resistings', 'forbid', 'countervails', 'disarmed', 'stabilising', 'cooperating', 'deter', 'powers', 'preventable', 'punitives', 'forbidden', 'hostages', 'armistices', 'retaliations', 'interdiction', 'cooperated', 'disarmament', 'revenge', 'uncooperating', 'sovereignties', 'toughenings', 'sanctionings', 'sanctioning', 'protector', 'armistice', 'liberate', 'tactically', 'control', 'expedite', 'intervene', 'cooperateds', 'monitors', 'forbids', 'liberation', 'expedites', 'preemptivelies', 'tacticians', 'preempted', 'prevention', 'compel', 'worsenings', 'overdues', 'tackle', 'preemption', 'preemptively', 'tactics', 'interdependences', 'compels', 'lawfullies', 'forced', 'power', 'counterinsurgencies', 'counteracts', 'securities', 'abates', 'abolish', 'concessions', 'disarm', 'protective', 'halt', 'enforcement', 'retaliate', 'abatements', 'protectorate', 'counterterrorisms', 'deters', 'compelling', 'homeland', 'securitys', 'countervailing', 'curb', 'monitor', 'cooperatings', 'curbs', 'protections', 'deterioratings', 'liberateds', 'preventables', 'controllings', 'prevent', 'nonproliferations', 'toughen', 'counterinsurgents', 'enforcements', 'preventative', 'counterterrorism', 'anarchy', 'protectivelies', 'preempteds', 'ceasefire', 'toughens', 'uncooperatives', 'resist', 'deporteds']
oops, in justification terms I forgot to assign a signal to these terms: ['age verifications', 'ticking clocks', "can't accept", 'counter-attacks', 'counter-attack', 'subject toes', "can't waits", 'protect frontline', 'decisive actions', 'protecting people', 'stop the boat', 'commanders-in-chief', 'tipping point', 'crack down', 'commanderss-in-chief', 'without delay', 'crack downs', 'fast tracks', 'age limits', 'cannot wait', 'ticking clock', 'tougher sentencing', "won't accepts", 'age limit', "won't accept", 'not accepts', 'break frees', 'protect frontlines', 'subject to', 'stronger controls', 'cannot waits', 'protecting peoples', 'stop the boats', 'tipping points', 'commander-in-chief', 'without delays', 'not accept', 'break free', "can't accepts", 'fast track', 'stronger control', "can't wait", 'stop brexits', 'tougher sentencings', "don't accepts", 'age verification', 'stop brexit', 'decisive action', "don't accept"]

In [17]:
# now these are displayed for visual inspection
all_categorised_securised_word_and_terms= [
    ("Threat Words", threat_seed_lexicon_words_signal_categories),
    ("Threat Terms", threat_seed_lexicon_terms_signal_categories),
    ("Urgency Words", urgency_seed_lexicon_words_signal_categories),
    ("Urgency Terms", urgency_seed_lexicon_terms_signal_categories),
    ("Justification Words", justification_of_extr_power_seed_lexicon_words_signal_categories),
    ("Justification Terms", justification_of_extr_power_seed_lexicon_terms_signal_categories)
]
pd.set_option('display.max_colwidth', None) # (looks better in dynamic sizing)
pd.set_option('display.max_rows', None)

# here I define the custom order for signal type
tier_order_to_display= ['core', 'secondary', 'contextual', 'n/a']

for name_of_lexicon, data_dict in all_categorised_securised_word_and_terms:
    lex_df= pd.DataFrame(list(data_dict.items()), columns=[name_of_lexicon.split()[0], 'Signal Type'])
    lex_df['Signal Type']= pd.Categorical(lex_df['Signal Type'], categories=tier_order_to_display, ordered=True)
    lex_df= lex_df.sort_values('Signal Type')
    print(f"\n Now I've categorised {name_of_lexicon}:")
    display(lex_df)

 Now I've categorised Threat Words:

                 Threat Signal Type
250          extinction        core
306             attacks        core
173            survival        core
344               wound        core
238           extremist        core
624              deaths        core
29                 wars        core
594            monsters        core
388           extremism        core
226           drownings        core
317        terminations        core
371            security        core
242           survivals        core
221        catastrophes        core
42               attack        core
574         catastrophe        core
611         termination        core
451            fatality        core
566          terminated        core
253                 war        core
361            drowning        core
447          securities        core
85              monster        core
82           extremisms        core
234              wounds        core
394               peril        core
403             threats        core
80             invading        core
78         catastrophic        core
475          fatalities        core
124              threat        core
571            invasion        core
181           invadings        core
581               death        core
231              perils        core
649         extinctions        core
491           invasions        core
429          extremists        core
572             illegal   secondary
589             fragile   secondary
598            hostiles   secondary
153          vulnerable   secondary
57             ruthless   secondary
389               grave   secondary
141           espionage   secondary
275       vulnerability   secondary
446         vulnerables   secondary
450           terrorist   secondary
133          espionages   secondary
440              demise   secondary
109             menaces   secondary
16               brutal   secondary
552               enemy   secondary
642             demises   secondary
246          terrorists   secondary
269         counterfeit   secondary
337              menace   secondary
495             vicious   secondary
423           barbarian   secondary
416        infiltrating   secondary
424          barbarians   secondary
335             enemies   secondary
35        infiltrations   secondary
315        counterfeits   secondary
307     vulnerabilities   secondary
558             hostile   secondary
168       infiltratings   secondary
412        infiltration   secondary
402                wave  contextual
331               virus  contextual
158                9/11  contextual
353              rwanda  contextual
622               blitz  contextual
103             rwandan  contextual
471               waves  contextual
515            illegals  contextual
105             viruses  contextual
287                 7/7  contextual
430         afghanistan         n/a
437          israelites         n/a
439               rival         n/a
438           authority         n/a
432        illegalities         n/a
433               crime         n/a
434          weaponizes         n/a
435          insurgents         n/a
431       disintegrates         n/a
436          separatist         n/a
0               suicide         n/a
442      militarisation         n/a
477          repressive         n/a
476                 wmd         n/a
474            combated         n/a
473           disasters         n/a
472            alqaedas         n/a
470           fightings         n/a
469     radicalisations         n/a
468       radicalisings         n/a
467      destabilizings         n/a
466             wartime         n/a
465        assassinates         n/a
464             guevara         n/a
463        terrorizings         n/a
441            violence         n/a
462              sarins         n/a
460               evils         n/a
459                kill         n/a
458          weaponised         n/a
457      deterioratings         n/a
456        destabilizes         n/a
455         capitulated         n/a
454          palestines         n/a
453             illicit         n/a
452       capitulations         n/a
448         violentlies         n/a
445           palestine         n/a
444            insecure         n/a
443          weaponises         n/a
461                army         n/a
449         illegallies         n/a
410           hegemonic         n/a
427            weaponry         n/a
367        insecurities         n/a
368              battle         n/a
369     fundamentalisms         n/a
370              viruse         n/a
372         terroristic         n/a
373                coup         n/a
366             radical         n/a
374               crise         n/a
376           coercives         n/a
377            warfield         n/a
378              armies         n/a
379            chemical         n/a
380            armament         n/a
381              blocks         n/a
375          separatism         n/a
382             warfare         n/a
365                 arm         n/a
363          destructor         n/a
347            firearms         n/a
348             killers         n/a
349             nuclear         n/a
350             blocked         n/a
351       criminalizing         n/a
352            suicides         n/a
364       deteriorateds         n/a
354      assassinatings         n/a
356             muslims         n/a
357         authorities         n/a
358            factions         n/a
359          terrorises         n/a
360            division         n/a
362             rwandas         n/a
355           explosive         n/a
428             racists         n/a
383            armories         n/a
385      assassinations         n/a
409               salws         n/a
478            pakistan         n/a
411         superpowers         n/a
413           chechnyas         n/a
414       surveillances         n/a
415    criminalisations         n/a
408            islamist         n/a
417        infiltrators         n/a
419          dominantly         n/a
420       nationalistic         n/a
421        afghanistans         n/a
422               gulfs         n/a
425           illegally         n/a
426          weaponries         n/a
418            killings         n/a
384             crimean         n/a
407          kurdistans         n/a
405              armour         n/a
386       deterioration         n/a
387         radicalises         n/a
390          radicalism         n/a
391           explosion         n/a
392              bomber         n/a
393       threateningly         n/a
406          infiltrate         n/a
395              coerce         n/a
397             firearm         n/a
398             bombard         n/a
399               arabs         n/a
400             netwars         n/a
401        nationalists         n/a
404          ballistics         n/a
396    criminalizations         n/a
479           dominants         n/a
497       destabilising         n/a
481        threatenings         n/a
590            coercion         n/a
591                gaza         n/a
592               nazis         n/a
593            crimeans         n/a
595             bombeds         n/a
596        insurgencies         n/a
597          warfighter         n/a
599              crises         n/a
600                drug         n/a
601          radicalise         n/a
602                iraq         n/a
603              libyas         n/a
604            husseins         n/a
605              fights         n/a
606            inhumans         n/a
588               daesh         n/a
607           weaponize         n/a
587      radicalisation         n/a
585           attackeds         n/a
565            fighting         n/a
567              crimea         n/a
568           genocides         n/a
569          militaries         n/a
570       capitulatings         n/a
573     fundamentalists         n/a
575         trafficking         n/a
576             bombers         n/a
577         terrorizing         n/a
578             wargame         n/a
579            assassin         n/a
580              blitzz         n/a
582      proliferations         n/a
583            casualty         n/a
584            somalias         n/a
586         criminalize         n/a
608            disaster         n/a
609           warmonger         n/a
610             lebanon         n/a
634             invades         n/a
635              combat         n/a
636               bombs         n/a
637             vietnam         n/a
638       destructively         n/a
639           terrorism         n/a
640        traffickings         n/a
641         bombardment         n/a
643         infiltrated         n/a
644          destructed         n/a
645              forces         n/a
646            attacked         n/a
647        militariseds         n/a
648        radicalising         n/a
650       criminalizeds         n/a
633           seapowers         n/a
632           airpowers         n/a
631             bombing         n/a
630             islamic         n/a
612            coercive         n/a
613         disobedient         n/a
614               force         n/a
615             killing         n/a
616            rwandans         n/a
617                iran         n/a
618          bombshells         n/a
564            killzone         n/a
619       assassinating         n/a
621             coerced         n/a
623            interpol         n/a
625             cluster         n/a
626               osces         n/a
627         warfighting         n/a
628           violences         n/a
629             crimeas         n/a
620           shortages         n/a
480          insurgency         n/a
563               sarin         n/a
561         cybersphere         n/a
504     radicalizations         n/a
505       disintegrated         n/a
506             hazards         n/a
507          explosions         n/a
508            assaults         n/a
509           combating         n/a
510           bombarded         n/a
511                iras         n/a
512         threatening         n/a
513        radicalizing         n/a
514            missiles         n/a
516              killer         n/a
517         existential         n/a
518            dictator         n/a
519              salwar         n/a
503           terrorize         n/a
520         capitulates         n/a
502         destructors         n/a
500                wmds         n/a
482           guerrilla         n/a
483          weaponized         n/a
484                nazi         n/a
485         radicalised         n/a
486         destabilize         n/a
487          terrorizes         n/a
488               block         n/a
489               hamas         n/a
490         warfighters         n/a
492            airpower         n/a
493          bombardeds         n/a
494        criminalises         n/a
496           dictators         n/a
498         deteriorate         n/a
499         radicalized         n/a
501         explosively         n/a
521             aegises         n/a
522           attackers         n/a
523             armings         n/a
544               kills         n/a
545          militarism         n/a
546            lebanons         n/a
547            radicals         n/a
548            violents         n/a
549                abms         n/a
550                 abm         n/a
551       warmongerings         n/a
553       antipersonnel         n/a
554         repressives         n/a
555      deteriorations         n/a
556       disobediences         n/a
557                evil         n/a
559           kurdistan         n/a
560        forcefullies         n/a
543         militarists         n/a
542           pakistans         n/a
541       proliferation         n/a
540        militarizeds         n/a
524         destabilise         n/a
525            attacker         n/a
526          combatings         n/a
527       destructibles         n/a
528         aggressions         n/a
529           nagasakis         n/a
530                 ira         n/a
562               iraqs         n/a
531               gangs         n/a
533         bombardings         n/a
534        criminalised         n/a
535                arms         n/a
536         lawbreakers         n/a
537          lawbreaker         n/a
538             hussein         n/a
539       destabilizeds         n/a
532        radicalizeds         n/a
346             battles         n/a
326          illegality         n/a
343          combatants         n/a
108            shortage         n/a
110          blockading         n/a
111         weaponiseds         n/a
112           hezbollah         n/a
113           woundings         n/a
114           terrorise         n/a
115            dominate         n/a
116          terrorisms         n/a
117        deteriorates         n/a
118            vietnams         n/a
119        criminalized         n/a
120         militarisms         n/a
121              racism         n/a
122          blockadeds         n/a
123        bombardments         n/a
107          bombarding         n/a
125             warhead         n/a
106              terror         n/a
102           partisans         n/a
87              invaded         n/a
88            combatant         n/a
89           explosives         n/a
90        destabilizing         n/a
91            lawlesses         n/a
92            assassins         n/a
93     nationalisations         n/a
94         dominantlies         n/a
95           hegemonics         n/a
96          terrorising         n/a
97          militarised         n/a
98        militaristics         n/a
99                 hama         n/a
100     destructivelies         n/a
101          combatting         n/a
104      radicalization         n/a
86           attackings         n/a
126           blockades         n/a
128        terroristics         n/a
150            viciouse         n/a
151    catastrophically         n/a
152          dominators         n/a
154         dominations         n/a
155           hazardous         n/a
156       criminaliseds         n/a
157              hazard         n/a
159               coups         n/a
160            colonial         n/a
161          hegemonies         n/a
162            wounding         n/a
163            threaten         n/a
164         separatists         n/a
165            bombings         n/a
166              invade         n/a
149           hiroshima         n/a
127               irans         n/a
148          terrorised         n/a
146          killswitch         n/a
129         blockadings         n/a
130            diseases         n/a
131              israel         n/a
132         weaponizeds         n/a
134      nationalistics         n/a
135             armours         n/a
136             traffic         n/a
137              atomic         n/a
138              armory         n/a
139             disease         n/a
140           cyberwars         n/a
142            warpaths         n/a
143      fundamentalism         n/a
144         terroriseds         n/a
145         infiltrates         n/a
147            dominant         n/a
84         criminallies         n/a
83              armoury         n/a
81             chechnya         n/a
21               arming         n/a
22                drugs         n/a
23            combateds         n/a
24         destructible         n/a
25              faction         n/a
26            interpols         n/a
27              killeds         n/a
28               aegise         n/a
30          traffickers         n/a
31      militarizations         n/a
32             blockade         n/a
33           dominances         n/a
34                 gang         n/a
36          terrorizeds         n/a
37          biologicals         n/a
20             guevaras         n/a
38               rivals         n/a
19           casualties         n/a
17          nationalist         n/a
1             chemicals         n/a
2                killed         n/a
3        disintegration         n/a
4                natoes         n/a
5                  gulf         n/a
6            warmongers         n/a
7                strike         n/a
8               kurdish         n/a
9              armoured         n/a
10               bombed         n/a
11               crimes         n/a
12         surveillance         n/a
13             warheads         n/a
14             wargames         n/a
15               bullet         n/a
18         capitulating         n/a
39            threatens         n/a
40             conflict         n/a
41                  fln         n/a
64            munitions         n/a
65             warplane         n/a
66            killzones         n/a
67              invader         n/a
68               weapon         n/a
69            landmines         n/a
70        lawlessnesses         n/a
71               target         n/a
72          destructeds         n/a
73             munition         n/a
74          hazardouses         n/a
75         existentials         n/a
76           guerrillas         n/a
77             narcotic         n/a
79              atomics         n/a
63             seapower         n/a
62                 nato         n/a
61             coercing         n/a
60           radicalize         n/a
43              assault         n/a
44             illicits         n/a
45         infiltrateds         n/a
46        radicalizings         n/a
47   catastrophicallies         n/a
48             invaders         n/a
49             islamics         n/a
167           coercings         n/a
50               racist         n/a
52              violent         n/a
53          destruction         n/a
54            violently         n/a
55          militarized         n/a
56             invadeds         n/a
58           trafficker         n/a
59          traffickeds         n/a
51            islamists         n/a
169             alqaeda         n/a
170         radicalizes         n/a
171             racisms         n/a
281      militarization         n/a
282        warfightings         n/a
283           armouries         n/a
284        terrorisings         n/a
285             weapons         n/a
286             combats         n/a
288           insecures         n/a
289     nationalisation         n/a
290          hezbollahs         n/a
291             missile         n/a
292           criminals         n/a
293         lawlessness         n/a
294        capitulateds         n/a
295            bombards         n/a
296        destructions         n/a
280     militarisations         n/a
297           conflicts         n/a
279          hazardouse         n/a
277              crisis         n/a
260             lawless         n/a
261       assassination         n/a
262      fundamentalist         n/a
263         separatisms         n/a
264            traffics         n/a
265     disintegratings         n/a
266           divisions         n/a
267          domination         n/a
268           blockaded         n/a
270               gazas         n/a
271           armoureds         n/a
272         threateneds         n/a
273         dominatings         n/a
274               fight         n/a
276            genocide         n/a
278      destabilisings         n/a
298             coerces         n/a
299                kurd         n/a
300        assassinated         n/a
325            woundeds         n/a
651        deteriorated         n/a
327               natoe         n/a
328             fighter         n/a
329            israelis         n/a
330               aegis         n/a
332     criminalisation         n/a
333            hegemony         n/a
334             bullets         n/a
336             terrors         n/a
338        disobedience         n/a
339         radicalisms         n/a
340            clusters         n/a
341           ballistic         n/a
342        cyberspheres         n/a

 Now I've categorised Threat Terms:

                 Threat Signal Type
20         cogs of wars        core
35           war engine        core
45          war machine        core
33   existential threat        core
32          cogs of war        core
31  existential threats        core
29       serious threat        core
25         war machines        core
18        engine of war        core
16          war engines        core
41           fight back        core
7       serious threats        core
51         under attack   secondary
21      invisible enemy   secondary
28    invisible enemies   secondary
11    illegal immigrant  contextual
39           new verdun  contextual
44         pearl harbor  contextual
1           nine eleven  contextual
2               wars on  contextual
3      illegal migrants  contextual
53          seven seven  contextual
30            world war  contextual
6            world wars  contextual
54           sea powers  contextual
26               war on  contextual
23            sea power  contextual
22              at wars  contextual
40        under attacks  contextual
19          new verduns  contextual
15   illegal immigrants  contextual
47             a cancer  contextual
13               at war  contextual
24      illegal migrant  contextual
49         the troubles         n/a
52          day slavery         n/a
46       arm industries         n/a
50        day slaveries         n/a
43       toxic legacies         n/a
42           our threat         n/a
48         arm industry         n/a
0          seven-sevens         n/a
27    being radicalised         n/a
37          our threats         n/a
36        fuel conflict         n/a
34         prisoners of         n/a
17  security priorities         n/a
14          the trouble         n/a
12        prisoners ofs         n/a
10          seven-seven         n/a
9    being radicaliseds         n/a
8          nine-elevens         n/a
5           nine-eleven         n/a
4        fuel conflicts         n/a
38    security priority         n/a
55         toxic legacy         n/a

 Now I've categorised Urgency Words:

            Urgency Signal Type
11          urgents        core
48    unprecedented        core
36           crises        core
10           crisis        core
9         immediate        core
56     unparalleled        core
45           urgent        core
40            react   secondary
30         urgently   secondary
47         reaction   secondary
50        reactions   secondary
29           reacts   secondary
35        paramount   secondary
59  inevitabilities  contextual
12    inevitability  contextual
53       inevitable  contextual
39         collapse         n/a
41           scarce         n/a
42       collapsing         n/a
43          tackles         n/a
38      escalations         n/a
44      spirallings         n/a
37         escalate         n/a
0            demand         n/a
49     imminentlies         n/a
52        collapses         n/a
54      armageddons         n/a
55        collapsed         n/a
57        imminents         n/a
58      escalatings         n/a
60      collapsings         n/a
61        emergency         n/a
62         scarcity         n/a
63     irreversible         n/a
46       scarcities         n/a
51    irreversibles         n/a
32            swift         n/a
33          demands         n/a
1            swifts         n/a
2           scarces         n/a
3        armageddon         n/a
4          mounting         n/a
5        worsenings         n/a
6          overdues         n/a
7            tackle         n/a
8        escalation         n/a
13           ensure         n/a
14          overdue         n/a
15        mountings         n/a
16         critical         n/a
34        criticals         n/a
17       collapseds         n/a
19          overrun         n/a
20         imminent         n/a
21       imminently         n/a
22      emergencies         n/a
23        escalates         n/a
24        worsening         n/a
25      immediately         n/a
26          ensures         n/a
27       escalating         n/a
28         overruns         n/a
31         scarcely         n/a
64       spiralling         n/a
18       scarcelies         n/a
65    immediatelies         n/a

 Now I've categorised Urgency Terms:

                 Urgency Signal Type
44     urgent priorities        core
61    point of no return        core
2                act now        core
20      supreme priority        core
19              too late        core
7     supreme priorities        core
14       urgent priority        core
41      life threatening        core
28         mustn't delay   secondary
17          cannot delay   secondary
35            can't wait   secondary
15           can't delay   secondary
36      decisive actions   secondary
25        must not delay   secondary
49       decisive action   secondary
5            cannot wait   secondary
57      immediate action   secondary
26     immediate actions   secondary
46          move rapidly  contextual
47  before the elections  contextual
48          swiftly move  contextual
29          quickly move  contextual
59          rapidly move  contextual
0         ticking clocks  contextual
32          move quickly  contextual
16         rapidly moves  contextual
11          move swiftly  contextual
6             any longer  contextual
13         quickly moves  contextual
3    before the election  contextual
9          ticking clock  contextual
18         swiftly moves  contextual
58            on day one         n/a
4         tipping points         n/a
56           wakeup call         n/a
8             strive for         n/a
1          without delay         n/a
55         now or nevers         n/a
54             make sure         n/a
53        breaking point         n/a
52          last chances         n/a
51          from day one         n/a
50             push toes         n/a
62         tipping point         n/a
63    threatening crisis         n/a
60           strive fors         n/a
23         end degrading         n/a
45        growing crises         n/a
24    threatening crises         n/a
22          now or never         n/a
27       national crises         n/a
21     life-threatenings         n/a
30       breaking points         n/a
31               push to         n/a
64           on day ones         n/a
33       national crisis         n/a
34            make sures         n/a
37         from day ones         n/a
38          wakeup calls         n/a
39        end degradings         n/a
40           last chance         n/a
12        without delays         n/a
42         cannot afford         n/a
43        growing crisis         n/a
10      life-threatening         n/a
65        cannot affords         n/a

 Now I've categorised Justification Words:

           Justification Signal Type
118               sieges        core
212               curfew        core
54               curfews        core
112       counterattacks        core
232                siege        core
145        counterattack        core
240            sovereign   secondary
239         prerogatives   secondary
106               decree   secondary
166           sovereigns   secondary
225              protect   secondary
171             protects   secondary
41           prerogative   secondary
99               decrees   secondary
116            mobilizes  contextual
28              mobilise  contextual
158          suspensions  contextual
169        surveillances  contextual
177              surveil  contextual
160           suspension  contextual
22              surveils  contextual
90              sanction  contextual
188            sanctions  contextual
186            mobilises  contextual
251             lockdown  contextual
85              mobilize  contextual
6           surveillance  contextual
44             lockdowns  contextual
191             expedite         n/a
190              control         n/a
189           tactically         n/a
179        uncooperating         n/a
187             liberate         n/a
172           armistices         n/a
173         retaliations         n/a
183          sanctioning         n/a
175           cooperated         n/a
176          disarmament         n/a
178              revenge         n/a
180        sovereignties         n/a
185            armistice         n/a
184            protector         n/a
181          toughenings         n/a
182         sanctionings         n/a
174         interdiction         n/a
0            resistances         n/a
168            forbidden         n/a
140          preventings         n/a
141             controls         n/a
142         intervention         n/a
143        uncooperative         n/a
144            embargoes         n/a
146         tacticallies         n/a
147          retaliation         n/a
148            abolishes         n/a
149          containment         n/a
150            anarchies         n/a
151             détentes         n/a
152              deports         n/a
153          preventions         n/a
154              hostage         n/a
155           resistings         n/a
156               forbid         n/a
157         countervails         n/a
159             disarmed         n/a
161          stabilising         n/a
162          cooperating         n/a
163                deter         n/a
164               powers         n/a
192            intervene         n/a
165          preventable         n/a
167            punitives         n/a
170             hostages         n/a
193          cooperateds         n/a
199           tacticians         n/a
195              forbids         n/a
230               deters         n/a
231           compelling         n/a
233             homeland         n/a
234            securitys         n/a
235       countervailing         n/a
236                 curb         n/a
237              monitor         n/a
238         cooperatings         n/a
241                curbs         n/a
242          protections         n/a
243       deterioratings         n/a
244           liberateds         n/a
245         preventables         n/a
246         controllings         n/a
247              prevent         n/a
248    nonproliferations         n/a
249              toughen         n/a
250    counterinsurgents         n/a
252         enforcements         n/a
253         preventative         n/a
254     counterterrorism         n/a
255              anarchy         n/a
256       protectivelies         n/a
257           preempteds         n/a
258            ceasefire         n/a
259             toughens         n/a
260       uncooperatives         n/a
229    counterterrorisms         n/a
228         protectorate         n/a
227           abatements         n/a
226            retaliate         n/a
196           liberation         n/a
197            expedites         n/a
198       preemptivelies         n/a
139            detterent         n/a
200            preempted         n/a
201           prevention         n/a
202               compel         n/a
203           worsenings         n/a
204             overdues         n/a
205               tackle         n/a
206           preemption         n/a
207         preemptively         n/a
208              tactics         n/a
194             monitors         n/a
209     interdependences         n/a
211           lawfullies         n/a
213               forced         n/a
214                power         n/a
215  counterinsurgencies         n/a
216          counteracts         n/a
217           securities         n/a
218               abates         n/a
219              abolish         n/a
220          concessions         n/a
221               disarm         n/a
222           protective         n/a
223                 halt         n/a
224          enforcement         n/a
210              compels         n/a
138           deterrence         n/a
131       conciliatories         n/a
136          stabiliseds         n/a
36          protectively         n/a
37             stabilise         n/a
38             tactician         n/a
39                remove         n/a
40             deterreds         n/a
42       interdependence         n/a
43            introduces         n/a
45              enforces         n/a
46              prevents         n/a
47            protection         n/a
48             disarming         n/a
49                tactic         n/a
50              haltings         n/a
51            forbidding         n/a
52         deteriorating         n/a
53             abatement         n/a
55       interdependents         n/a
56               embargo         n/a
57           sanctioneds         n/a
58           cooperation         n/a
59            crackdowns         n/a
60              tactical         n/a
61            stabilises         n/a
62            compromise         n/a
63              deterred         n/a
64              overhaul         n/a
65               rescues         n/a
35            tougheneds         n/a
34               demands         n/a
33           liberatings         n/a
32               détente         n/a
1             stabilised         n/a
2             abolitions         n/a
3           stabilisings         n/a
4        countervailings         n/a
5             preventive         n/a
7                disarms         n/a
8              disarmeds         n/a
9                 defend         n/a
10               enforce         n/a
11         protectorates         n/a
12      nonproliferation         n/a
13           countervail         n/a
14             toughened         n/a
66                deport         n/a
15             tacticals         n/a
17          conciliatory         n/a
18           forbiddings         n/a
19              oversees         n/a
20            sanctioned         n/a
21     counterinsurgency         n/a
23               resists         n/a
24              resisted         n/a
25              preempts         n/a
26           sovereignty         n/a
27           controlling         n/a
29           liberations         n/a
30             resisting         n/a
31             abolition         n/a
16           detterences         n/a
137              removes         n/a
67               forceds         n/a
69            retaliates         n/a
105                abate         n/a
107               rescue         n/a
108            homelands         n/a
109              tackles         n/a
110           concession         n/a
111            liberated         n/a
113                halts         n/a
114            liberates         n/a
115           preemptive         n/a
117         containments         n/a
119             deported         n/a
120             revenges         n/a
121              oversee         n/a
122           detterence         n/a
123        interventions         n/a
124               demand         n/a
125           intervenes         n/a
126           counteract         n/a
127           preventing         n/a
128           forbiddens         n/a
129          deterrences         n/a
130          compellings         n/a
261               resist         n/a
132          compromises         n/a
133            cooperate         n/a
134              preempt         n/a
135         conciliation         n/a
104     counterinsurgent         n/a
103             security         n/a
102          preemptives         n/a
101         cooperations         n/a
70            liberating         n/a
71          disarmaments         n/a
72            detterents         n/a
73           preventives         n/a
74            liberators         n/a
75             liberator         n/a
76         preventatives         n/a
77            disarmings         n/a
78               overdue         n/a
79         conciliations         n/a
80             crackdown         n/a
81              lawfully         n/a
82             overhauls         n/a
68              punitive         n/a
83        uncooperatings         n/a
86           preemptions         n/a
87           protectives         n/a
88            toughening         n/a
89            ceasefires         n/a
91            cooperates         n/a
92             worsening         n/a
93             resisteds         n/a
94            resistance         n/a
95            protectors         n/a
96         interdictions         n/a
97             introduce         n/a
98        interdependent         n/a
100              halting         n/a
84               defends         n/a
262            deporteds         n/a

 Now I've categorised Justification Terms:

             Justification Signal Type
45      state of emergency        core
28    state of emergencies        core
66           restore order        core
12          counter attack        core
62            martial laws        core
10         counter attacks        core
51     extraordinary means        core
69  extraordinary measures        core
41              fight back        core
74             martial law        core
3            breaking free        core
2      exceptional measure        core
47       exceptional means        core
7     exceptional measures        core
71           solemn duties   secondary
67      commander in chief   secondary
64             solemn duty   secondary
27          maintain order   secondary
46         beyond politics   secondary
76          border closure  contextual
34       close our borders  contextual
54         border closures  contextual
31         shut our border  contextual
38        close our border  contextual
73        close the border  contextual
19        shut the borders  contextual
72       close the borders  contextual
14         shut the border  contextual
70        shut our borders  contextual
59              can't wait         n/a
75         decisive action         n/a
48          stop the boats         n/a
49          tipping points         n/a
50      commander-in-chief         n/a
52          without delays         n/a
68             stop brexit         n/a
53              not accept         n/a
65        age verification         n/a
55              break free         n/a
56           can't accepts         n/a
63           don't accepts         n/a
57              fast track         n/a
58        stronger control         n/a
60            stop brexits         n/a
61     tougher sentencings         n/a
0        age verifications         n/a
43            cannot waits         n/a
1           ticking clocks         n/a
4             can't accept         n/a
5          counter-attacks         n/a
6           counter-attack         n/a
8             subject toes         n/a
9              can't waits         n/a
11       protect frontline         n/a
13        decisive actions         n/a
15       protecting people         n/a
16           stop the boat         n/a
17     commanders-in-chief         n/a
18           tipping point         n/a
20              crack down         n/a
21    commanderss-in-chief         n/a
22           without delay         n/a
23             crack downs         n/a
24             fast tracks         n/a
25              age limits         n/a
26             cannot wait         n/a
29           ticking clock         n/a
30      tougher sentencing         n/a
32           won't accepts         n/a
33               age limit         n/a
35            won't accept         n/a
36             not accepts         n/a
37             break frees         n/a
39      protect frontlines         n/a
40              subject to         n/a
42       stronger controls         n/a
44      protecting peoples         n/a
77            don't accept         n/a

## 2. Expansion using a lexicon from the literature
Now I expand my lexicon using Baele and Sterck’s Security Lexicon (Baele & Sterk, 2014), which is a specialised dictionary of 222 words they claim unambiguously belongs to the "hard" security lexical field. The made it to measure the linguistic intensity of securitising moves, so it fits well here. This primarily supports Threat Construction ("war," "enemy"), but also support the Justification of Extraordinary Measures one a bit too (e.g. "measures," "defend").

If not already identified in securitisation literature, I use these words only be used as secondary or contextual signals unless they stand out as excpetionally relevant to securitisation.

It uses stemming, so I'm seperating the lexicon into 2 list to deal with the stemmed variants seperately. I don't want to assume each stemmed variant is semantically equal in intonation (e.g. "remove" carries different weight to "removal"), so a degree of manual oversight is needed on my end to ensure all word variants are given the right category.

The words here are *generic* "hard security" ones (per Baele & Rousseau's wording) i.e. they directly evoke a security threat regardless of context.

In [18]:
non_stemmed_SL = {"abatement", "abm", "afghanistan", "aggression", "airland", "airpower", "alliance", "alert", "alqaeda", "ammunition", "amphibious", "anarchy",
           "antipersonnel", "apt", "arab", "assault", "atomic", "authority", "baader", "balance", "ballistic", "battle", "bin", "biological", "bullet",
           "ceasefire", "chechnya", "chemical", "cluster", "colonial", "compromise", "concession", "counterterrorism", "coup", "crisis", "critical",
           "cybersphere", "cyberwar", "détente", "dictator", "dilemma", "disaster", "disease", "disobedience", "dispute", "division", "drugs", "embargo",
           "emergency", "enemy", "escalation", "evil", "existential", "expeditionary", "faction", "failed", "fear", "firearms", "fln", "freedom", "friction",
           "gang", "gaza", "genocide", "globalization", "guerrilla", "guevara", "gulf", "hamas", "hard", "hezbollah", "hiroshima", "homeland", "hostage",
           "hussein", "identity", "illicit", "incumbent", "inhuman", "intelligence", "interdiction", "interpol", "intervention", "ira", "iran", "iraq",
           "landmine", "lebanon", "libya", "malacca", "missile", "muslims", "nagasaki", "narcotics", "nato", "nazi", "netwar", "nonproliferation", "nuclear",
           "offensive", "oil", "osce", "pakistan", "palestine", "partisan", "police", "poverty", "power", "rescue", "resolution", "resources", "response",
           "retaliation", "revenge", "revolution", "rogue", "safe", "salt", "sarin", "seapower", "shock", "somalia", "state", "strike", "suicide",
           "superpower", "surge", "surveillance", "syria", "target", "transnational", "uprising", "values", "vietnam", "water", "wmd"}

stemmed_SL = {"arm", "assassi", "attack", "bipolar", "blitzkrieg", "block", "bomb", "capabilit", "capitulat", "casualt", "catastroph", "clos", "coerc", "collaps",
       "combat", "compel", "conciliat", "conflict", "contain", "control", "cooperat", "counteract", "counterinsurgen", "countervail", "crim", "damag",
       "danger", "defen", "demilitaris", "demobilis", "destab", "destruct", "deter", "disarm", "disintegrat", "domin", "explos", "fight", "forbid",
       "force", "fundamentalis", "hazard", "hegemon", "illegal", "imminen", "infiltrat", "insecur", "insurgen", "interdependen", "invade", "israel",
       "kill", "kurd", "law", "liberat", "militar", "munition", "nationalis", "overwhelm", "preempt", "prevent", "proliferat", "protect", "puniti",
       "racis", "radical", "resist", "rival", "salw", "sanction", "scarc", "secur", "separatis", "shortage", "sovereign", "stabilis", "strateg", "tactic",
       "terror", "threat", "traffic", "violen", "war", "weapon", "wound"}

non_stemmed_SL.remove("hard") # (I thought this was too generic & will get too many false positives in manifesto context)

In [22]:
# All words already present in the lexicons can just be dropped
# This has got to done before assigning signal type to though, to avoid variation in tier ranking
lexicon_dicts= [threat_seed_lexicon_words_signal_categories, threat_seed_lexicon_terms_signal_categories, urgency_seed_lexicon_words_signal_categories, urgency_seed_lexicon_terms_signal_categories, justification_of_extr_power_seed_lexicon_words_signal_categories, justification_of_extr_power_seed_lexicon_terms_signal_categories]
def drop_dupes_from_lexicon_tier(set_to_filter_out):
  original_lex_set= set_to_filter_out.copy()
  for lex_dict in lexicon_dicts:
    redundancy_check= set(lex_dict.keys())
    set_to_filter_out= set_to_filter_out - redundancy_check
  print(f"I droppped {original_lex_set - set_to_filter_out} words.")
  print("these are the ones remaining:")
  return set_to_filter_out

# Get shot of the non-stemmed dupes
drop_dupes_from_lexicon_tier(non_stemmed_SL)

I droppped {'suicide', 'guerrilla', 'gulf', 'aggression', 'strike', 'nazi', 'superpower', 'surveillance', 'alqaeda', 'hamas', 'inhuman', 'nonproliferation', 'airpower', 'bullet', 'netwar', 'détente', 'drugs', 'osce', 'faction', 'cyberwar', 'disobedience', 'gang', 'shock', 'ballistic', 'abatement', 'biological', 'nagasaki', 'embargo', 'emergency', 'firearms', 'fln', 'assault', 'compromise', 'existential', 'dictator', 'nuclear', 'syria', 'muslims', 'rogue', 'critical', 'ira', 'uprising', 'division', 'partisan', 'nato', 'seapower', 'battle', 'hussein', 'coup', 'rescue', 'arab', 'concession', 'target', 'abm', 'chemical', 'enemy', 'antipersonnel', 'libya', 'evil', 'cybersphere', 'narcotics', 'sarin', 'chechnya', 'somalia', 'landmine', 'intervention', 'retaliation', 'hostage', 'gaza', 'iraq', 'interdiction', 'disaster', 'hezbollah', 'revenge', 'lebanon', 'iran', 'afghanistan', 'authority', 'interpol', 'escalation', 'cluster', 'crisis', 'genocide', 'power', 'palestine', 'atomic', 'disease', 'illicit', 'vietnam', 'missile', 'homeland', 'hiroshima', 'colonial', 'guevara', 'counterterrorism', 'anarchy', 'ceasefire', 'wmd', 'pakistan'} words.
these are the ones remaining:

{'airland',
 'alert',
 'alliance',
 'ammunition',
 'amphibious',
 'apt',
 'baader',
 'balance',
 'bin',
 'dilemma',
 'dispute',
 'expeditionary',
 'failed',
 'fear',
 'freedom',
 'friction',
 'globalization',
 'identity',
 'incumbent',
 'intelligence',
 'malacca',
 'offensive',
 'oil',
 'police',
 'poverty',
 'resolution',
 'resources',
 'response',
 'revolution',
 'safe',
 'salt',
 'state',
 'surge',
 'transnational',
 'values',
 'water'}

In [23]:
# A list of commonly used terms are used here to produce variants of the stems provided by the SL
big_list_of_english_words= set(wordfreq.top_n_list("en", n=100000))

# I have this helper to search for matches given a root word
def expand_the_root_word(stem, vocab):
    return sorted({word for word in vocab if word.startswith(stem) and len(word) > len(stem)})

# I call the helper here to find all matches (which need manual vetting as I set n as quite high above, so some false +ve's are inevitable)
expanded_SL_lexicon_terms= {
    stem: expand_the_root_word(stem, big_list_of_english_words)
    for stem in stemmed_SL
}


# Now I create the data structure to hold the lexicon creation up to this point.
lexicon_rows= []
for root_word, variants_of_it in expanded_SL_lexicon_terms.items():
    for variant_of_word in variants_of_it:
        lexicon_rows.append({
            "root": root_word, "variant": variant_of_word,
            # these other 3 cols are useful when analysing these words in excel
            "keep": "", "tier": "",  # core, secondary & contextual signals
            "notes": "" # (just for my own purpose really, if I want to make a note about that particular word)
        })
stem_df= pd.DataFrame(lexicon_rows)
stem_df

                root            variant keep tier notes
0            hegemon          hegemonic
1            hegemon           hegemony
2             invade            invaded
3             invade            invader
4             invade           invaders
5             invade            invades
6            illegal         illegality
7            illegal          illegally
8            illegal           illegals
9         counteract       counteracted
10        counteract      counteracting
11        counteract        counteracts
12             block            block's
13             block           blockade
14             block          blockaded
15             block          blockades
16             block         blockading
17             block           blockage
18             block          blockages
19             block        blockbuster
20             block       blockbusters
21             block         blockchain
22             block        blockchains
23             block            blocked
24             block            blocker
25             block           blockers
26             block          blockhead
27             block         blockheads
28             block         blockhouse
29             block           blocking
30             block             blocks
31             block             blocky
32           casualt         casualties
33           casualt           casualty
34           preempt          preempted
35           preempt         preemption
36           preempt         preemptive
37           preempt       preemptively
38       countervail     countervailing
39               law              law's
40               law              lawal
41               law        lawbreakers
42               law               lawd
43               law              lawes
44               law            lawford
45               law             lawful
46               law           lawfully
47               law         lawfulness
48               law           lawgiver
49               law             lawler
50               law            lawless
51               law        lawlessness
52               law             lawley
53               law             lawlor
54               law           lawmaker
55               law          lawmakers
56               law          lawmaking
57               law             lawman
58               law             lawmen
59               law               lawn
60               law           lawndale
61               law          lawnmower
62               law         lawnmowers
63               law              lawns
64               law           lawrence
65               law         lawrence's
66               law       lawrenceburg
67               law      lawrenceville
68               law             lawrie
69               law              lawry
70               law               laws
71               law             lawson
72               law           lawson's
73               law            lawsuit
74               law           lawsuits
75               law             lawton
76               law             lawyer
77               law           lawyer's
78               law          lawyering
79               law            lawyers
80           militar         militaries
81           militar         militarily
82           militar         militarism
83           militar         militarist
84           militar       militaristic
85           militar     militarization
86           militar        militarized
87           militar           military
88           militar         military's
89          cooperat          cooperate
90          cooperat         cooperated
91          cooperat         cooperates
92          cooperat        cooperating
93          cooperat        cooperation
94          cooperat        cooperative
95          cooperat      cooperatively
96          cooperat       cooperatives
97           collaps           collapse
98           collaps          collapsed
99           collaps          collapses
100          collaps        collapsible
101          collaps         collapsing
102          strateg          strategic
103          strateg        strategical
104          strateg      strategically
105          strateg         strategies
106          strateg         strategist
107          strateg        strategists
108          strateg         strategize
109          strateg       strategizing
110          strateg           strategy
111              war              war's
112              war            waratah
113              war           waratahs
114              war             warble
115              war            warbler
116              war           warblers
117              war           warbling
118              war            warburg
119              war          warburton
120              war              warby
121              war           warcraft
122              war               ward
123              war             ward's
124              war              warde
125              war             warded
126              war            wardell
127              war             warden
128              war           warden's
129              war            wardens
130              war             warder
131              war            warders
132              war            warding
133              war            wardlaw
134              war             wardle
135              war           wardrobe
136              war          wardrobes
137              war              wards
138              war               ware
139              war            wareham
140              war          warehouse
141              war         warehouses
142              war        warehousing
143              war              wares
144              war            warfare
145              war           warfarin
146              war           warfield
147              war         warfighter
148              war        warfighting
149              war           warframe
150              war               warg
151              war            wargame
152              war           wargames
153              war          wargaming
154              war          warhammer
155              war            warhawk
156              war            warhead
157              war           warheads
158              war             warhol
159              war           warhol's
160              war           warhorse
161              war             warily
162              war           wariness
163              war             waring
164              war              wario
165              war               wark
166              war            warlike
167              war            warlock
168              war           warlocks
169              war            warlord
170              war           warlords
171              war               warm
172              war             warmed
173              war             warmer
174              war            warmers
175              war            warmest
176              war            warming
177              war         warminster
178              war             warmly
179              war          warmonger
180              war       warmongering
181              war         warmongers
182              war              warms
183              war             warmth
184              war             warmup
185              war            warmups
186              war               warn
187              war              warne
188              war             warned
189              war             warner
190              war           warner's
191              war            warners
192              war            warning
193              war           warnings
194              war            warnock
195              war              warns
196              war               warp
197              war           warpaint
198              war            warpath
199              war             warped
200              war            warping
201              war           warplane
202              war          warplanes
203              war              warps
204              war               warr
205              war            warrant
206              war          warranted
207              war         warranties
208              war         warranting
209              war        warrantless
210              war           warrants
211              war           warranty
212              war             warren
213              war           warren's
214              war            warrens
215              war        warrensburg
216              war          warrenton
217              war              warri
218              war            warrick
219              war           warriner
220              war            warring
221              war          warringah
222              war         warrington
223              war            warrior
224              war          warrior's
225              war           warriors
226              war        warrnambool
227              war               wars
228              war             warsaw
229              war           warsaw's
230              war            warship
231              war           warships
232              war              warsi
233              war           warszawa
234              war               wart
235              war            warthog
236              war           warthogs
237              war            wartime
238              war             warton
239              war              warts
240              war              warty
241              war            warwick
242              war       warwickshire
243              war               wary
244              war            warzone
245      disintegrat       disintegrate
246      disintegrat      disintegrated
247      disintegrat      disintegrates
248      disintegrat     disintegrating
249      disintegrat     disintegration
250        conciliat       conciliation
251        conciliat       conciliatory
252           forbid          forbidden
253           forbid         forbidding
254           forbid            forbids
255            deter          detergent
256            deter         detergents
257            deter        deteriorate
258            deter       deteriorated
259            deter       deteriorates
260            deter      deteriorating
261            deter      deterioration
262            deter        determinant
263            deter       determinants
264            deter        determinate
265            deter      determination
266            deter     determinations
267            deter      determinative
268            deter          determine
269            deter         determined
270            deter       determinedly
271            deter         determiner
272            deter         determines
273            deter        determining
274            deter        determinism
275            deter      deterministic
276            deter           deterred
277            deter         deterrence
278            deter          deterrent
279            deter         deterrents
280            deter          deterring
281            deter             deters
282         stabilis      stabilisation
283         stabilis          stabilise
284         stabilis         stabilised
285         stabilis         stabiliser
286         stabilis        stabilisers
287         stabilis        stabilising
288        capitulat         capitulate
289        capitulat        capitulated
290        capitulat       capitulating
291        capitulat       capitulation
292           terror          terrorise
293           terror         terrorised
294           terror        terrorising
295           terror          terrorism
296           terror          terrorist
297           terror        terrorist's
298           terror        terroristic
299           terror         terrorists
300           terror          terrorize
301           terror         terrorized
302           terror         terrorizes
303           terror        terrorizing
304           terror            terrors
305        infiltrat         infiltrate
306        infiltrat        infiltrated
307        infiltrat        infiltrates
308        infiltrat       infiltrating
309        infiltrat       infiltration
310        infiltrat        infiltrator
311        infiltrat       infiltrators
312         shortage          shortages
313            coerc             coerce
314            coerc            coerced
315            coerc           coercing
316            coerc           coercion
317            coerc           coercive
318           tactic           tactical
319           tactic         tactically
320           tactic          tactician
321           tactic            tactics
322          liberat           liberate
323          liberat          liberated
324          liberat          liberates
325          liberat         liberating
326          liberat         liberation
327          liberat          liberator
328          liberat         liberators
329        capabilit       capabilities
330        capabilit         capability
331            force            force's
332            force             forced
333            force           forceful
334            force         forcefully
335            force            forceps
336            force             forces
337            wound            wounded
338            wound           wounding
339            wound             wounds
340         conflict         conflicted
341         conflict        conflicting
342         conflict          conflicts
343    interdependen    interdependence
344    interdependen     interdependent
345        separatis         separatism
346        separatis         separatist
347        separatis        separatists
348          control          control's
349          control    controllability
350          control       controllable
351          control         controlled
352          control         controller
353          control       controller's
354          control        controllers
355          control        controlling
356          control           controls
357           attack           attack's
358           attack           attacked
359           attack           attacker
360           attack         attacker's
361           attack          attackers
362           attack          attacking
363           attack            attacks
364            defen            defence
365            defen        defenceless
366            defen         defenceman
367            defen         defencemen
368            defen           defences
369            defen             defend
370            defen          defendant
371            defen        defendant's
372            defen         defendants
373            defen           defended
374            defen           defender
375            defen         defender's
376            defen          defenders
377            defen          defending
378            defen            defends
379            defen            defense
380            defen          defense's
381            defen        defenseless
382            defen         defenseman
383            defen         defensemen
384            defen           defenses
385            defen         defensible
386            defen          defensive
387            defen        defensively
388            defen      defensiveness
389            defen           defensor
390       proliferat        proliferate
391       proliferat       proliferated
392       proliferat      proliferating
393       proliferat      proliferation
394       proliferat      proliferative
395            fight          fightback
396            fight            fighter
397            fight          fighter's
398            fight           fighters
399            fight            fightin
400            fight           fighting
401            fight             fights
402           compel          compelled
403           compel         compelling
404           compel       compellingly
405           compel            compels
406           threat           threaten
407           threat         threatened
408           threat        threatening
409           threat      threateningly
410           threat          threatens
411           threat            threats
412            rival            rival's
413            rival            rivaldo
414            rival            rivaled
415            rival           rivaling
416            rival           rivalled
417            rival          rivalling
418            rival          rivalries
419            rival            rivalry
420            rival             rivals
421            scarc             scarce
422            scarc           scarcely
423            scarc            scarcer
424            scarc           scarcity
425       catastroph        catastrophe
426       catastroph       catastrophes
427       catastroph       catastrophic
428       catastroph   catastrophically
429            damag             damage
430            damag            damaged
431            damag            damages
432            damag           damaging
433           israel           israel's
434           israel            israeli
435           israel           israelis
436           israel          israelite
437           israel         israelites
438           israel            israels
439             salw              salwa
440             salw             salwar
441          insecur           insecure
442          insecur       insecurities
443          insecur         insecurity
444           explos          explosion
445           explos         explosions
446           explos          explosive
447           explos        explosively
448           explos      explosiveness
449           explos         explosives
450            secur             secure
451            secur            secured
452            secur           securely
453            secur            secures
454            secur           securing
455            secur         securities
456            secur     securitization
457            secur           security
458            secur         security's
459         insurgen       insurgencies
460         insurgen         insurgency
461         insurgen          insurgent
462         insurgen         insurgents
463           violen           violence
464           violen            violent
465           violen          violently
466           disarm        disarmament
467           disarm           disarmed
468           disarm          disarming
469           disarm            disarms
470           puniti           punitive
471         destruct         destructed
472         destruct       destructible
473         destruct        destructing
474         destruct        destruction
475         destruct       destructions
476         destruct        destructive
477         destruct      destructively
478         destruct    destructiveness
479         destruct         destructor
480          traffic         trafficked
481          traffic         trafficker
482          traffic        traffickers
483          traffic        trafficking
484          traffic           traffics
485        overwhelm        overwhelmed
486        overwhelm       overwhelming
487        overwhelm     overwhelmingly
488        overwhelm         overwhelms
489             clos              close
490             clos             closed
491             clos            closely
492             clos          closeness
493             clos           closeout
494             clos             closer
495             clos            closers
496             clos             closes
497             clos            closest

### Grading lexicon values
At this point I have a list of possible candidates for securitised language. Some of the stem variants will need to be dropped though because they don't resemble securitised language.

The remaining words then need to be assigned categories. As a reminder, primary signals are activley & unambigiously securitising, secondary signals activley intensify/accelarates/legitimises securitisation, whilst contextual signals condition interpretation but can aid securitisation in the right context.

To rank these, a human-in-the-loop approach is needed that doesn't soley rely on human opinion. Thus I use a gradingdefinition to account multiple converging signals but use human judement being the final decider.

The core question to be answered is: "If this word appears alone, does it push the utterance closer to a securitising move?"

However, whilst I take a common evalulation approach for all dimensions, this varies across securitisation dimensions, acknowledging their variation.

In [24]:
# Firstly, the non-securitising stems need to be dropped. This list was decided from a manual examination of the produced stems.
non_securitising_language= {
    "dangerfield", "salwa", "detergent", "detergents", "determinants",
    "determinate", "determination", "determinations", "determinative",
    "determinate", "determined", "determinedly", "determiner", "determines",
    "determining", "determinism", "deterministic", "domina", "dominatrix",
    "domine", "domineering", "domingo", "domingue", "dominguez", "domini",
    "dominic", "dominic's", "dominica", "dominican", "dominicans", "dominick",
    "dominik", "dominika", "dominique", "domino's", "dominus", "militarily",
    "cooperatives", "preventer", "resistor", "resistors", "lawal", "lawd",
    "lawes", "lawford", "lawgiver", "lawler", "lawley", "lawlor", "lawman",
    "lawmen", "lawn", "lawndale", "lawnmower", "lawnmowers", "lawns",
    "lawrence", "lawrence's", "lawrenceburg", "lawrenceville", "lawrie",
    "lawry", "lawson", "lawson's", "lawton", "lawyer", "lawyer's",
    "lawyering", "lawyers", "defenceman", "defencemen", "defendant",
    "defendant's", "defendants", "defense's", "defenseless", "defenseman",
    "defensemen", "defensible", "defensive", "defensively", "defensiveness",
    "defensor", "killa", "killah", "killam", "killarney", "killeen",
    "killen", "killian", "killick", "killin", "killington", "killjoy",
    "killjoys", "killua", "killy", "waratah", "waratahs", "warble",
    "warbler", "warblers", "warbling", "warburg", "warburton", "warby",
    "warcraft", "ward", "ward's", "warde", "warded", "wardell", "warden",
    "warden's", "wardens", "warder", "warders", "warding", "wardlaw",
    "wardle", "wardrobe", "wardrobes", "wards", "ware", "wareham",
    "warehouse", "warehouses", "warehousing", "wares", "warfarin",
    "warframe", "warg", "wargaming", "warhammer", "warhawk", "warhol",
    "warhol's", "warhorse", "warily", "wariness", "waring", "wario",
    "wark", "warlike", "warlock", "warlocks", "warlord", "warlords",
    "warm", "warmed", "warmer", "warmers", "warmest", "warming",
    "warminster", "warmly", "warms", "warmth", "warmup", "warmups",
    "warn", "warne", "warned", "warner", "warner's", "warners", "warning",
    "warnings", "warnock", "warns", "warp", "warpaint", "warped",
    "warping", "warps", "warr", "warrant", "warranted", "warranties",
    "warranting", "warrantless", "warrants", "warranty", "warren",
    "warren's", "warrens", "warrensburg", "warrenton", "warri", "warrick",
    "warriner", "warring", "warringah", "warrington", "warrior",
    "warrior's", "warriors", "warrnambool", "wars", "warsaw", "warsaw's",
    "warship", "warships", "warsi", "warszawa", "wart", "warthog",
    "warthogs", "warton", "warts", "warty", "warwick", "warwickshire",
    "wary", "warzone", "control's", "controller's", "controllers",
    "rivaldo", "fightin", "criminologist", "criminologists", "criminology",
    "crimp", "crimped", "crimping", "crimson", "block's", "blockage",
    "blockages", "blockbuster", "blockbusters", "blockchain", "blockchains",
    "blocker", "blockers", "blockhead", "blockheads", "blockhouse",
    "blocky", "forceps", "close", "closed", "closely", "closeness",
    "closeout", "closer", "closers", "closes", "closest", "closet",
    "closeted", "closets", "closeup", "closeups", "closing", "closings",
    "clostridium", "closure", "closures", "arm's", "arma", "armaan",
    "armada", "armadalearmadillo", "armadillos", "armagh", "armagnac",
    "arman", "armand", "armando", "armani", "armas", "armature", "armband",
    "armbands", "armbar", "armbruster", "armchair", "armchairs", "armee",
    "armen", "armenia", "armenia's", "armenian", "armenians", "armful",
    "armidale", "armie", "armin", "arminian", "arminius", "armisen",
    "armistead", "armitage", "armless", "armoire", "armond", "armonk",
    "armor", "armored", "armorial", "armories", "armors", "armpit",
    "armpits", "armrest", "armrests", "armstead", "armstrong",
    "armstrong's", "bomba", "bombast", "bombastic", "bombay",
    "bomberman", "container", "containers", "airland", "alert",
    "ammunition", "amphibious", "armadillo", "armadale", "baader",
    "balance", "bin", "law", "laws", "lawmaker", "lawmakers", "lawmaking",
    "lawsuit", "malacca", "salt", "securitization", "strategist", "strategists",
    "water", "hard",
}

# There are also some stems that should remain in their root form, that are dropped using the above method; here they're manually specified and re-included
securitising_stems= {"salw", "deter", "militarisation", "militarised", "uncooperating", "uncooperative", "uncooperativley", "strategise", "strategising", "resist",
                      "combat", "law", "weaponised", "weaponise", "sanctions", "counteract", "war", "counterinsurgent", "forbid", "rival", "shortage", "preempt",
                      "kurd", "israel", "countervail", "conflict", "terror", "radicalise", "radicalised", "radicalising", "radical", "contain", "hazard",
                      "abate", "disobedient", "esculate", "intervene", 'retaliate'}

# spellcheck (as these were manually typed) before dropping, or didn't include the English spelling (needed as these are British manifestos)
words_to_keep= {"salwa", "salw", "militarisation", "militarised", "weaponised", "weaponise", "strategise", "strategising", "radicalise", "radicalised",
                 "radicalising", "uncooperating", "uncooperativley", "killy", "warringah", "warhol's", "warde"}
spell_check_lexicon_words.known(list(words_to_keep))
#validate_lexicon_entries(non_securitising_language, "Non-securitising language (TO DROP)", words_to_keep)
validate_lexicon_entries(securitising_stems, "Securitising stems (TO RE-INCLUDE)", words_to_keep)

# Now the entire collection of valid roots and stems can be compiled
all_possible_variants= set(stem_df['variant'])
valid_variants= all_possible_variants - non_securitising_language
all_valid_stem_variants= securitising_stems.union(valid_variants).union(non_stemmed_SL)

print("\n Validated SL terms:")
display(all_valid_stem_variants)

 now spell checking for Securitising stems (TO RE-INCLUDE)...
the misspelled words in Securitising stems (TO RE-INCLUDE) are: {'esculate': 'escalate'}
so the corrected ones in Securitising stems (TO RE-INCLUDE) were: {'intervene', 'radicalised', 'counteract', 'rival', 'militarisation', 'israel', 'preempt', 'countervail', 'law', 'uncooperative', 'militarised', 'strategising', 'war', 'retaliate', 'contain', 'combat', 'forbid', 'radical', 'deter', 'terror', 'escalate', 'counterinsurgent', 'radicalise', 'abate', 'shortage', 'uncooperativley', 'weaponised', 'strategise', 'uncooperating', 'kurd', 'hazard', 'radicalising', 'weaponise', 'disobedient', 'conflict', 'sanctions', 'resist', 'salw'}
Great, the Securitising stems (TO RE-INCLUDE) lexicon is now all validated.

 Validated SL terms:

{'abate',
 'abatement',
 'abm',
 'afghanistan',
 'aggression',
 'airland',
 'airpower',
 'alert',
 'alliance',
 'alqaeda',
 'ammunition',
 'amphibious',
 'anarchy',
 'antipersonnel',
 'apt',
 'arab',
 'armageddon',
 'armament',
 'armaments',
 'armed',
 'armes',
 'armies',
 'arming',
 'armistice',
 'armory',
 'armour',
 'armoured',
 'armoury',
 'arms',
 'army',
 "army's",
 'armys',
 'assassin',
 "assassin's",
 'assassinate',
 'assassinated',
 'assassinating',
 'assassination',
 'assassinations',
 'assassins',
 'assault',
 'atomic',
 "attack's",
 'attacked',
 'attacker',
 "attacker's",
 'attackers',
 'attacking',
 'attacks',
 'authority',
 'baader',
 'balance',
 'ballistic',
 'battle',
 'bin',
 'biological',
 'blockade',
 'blockaded',
 'blockades',
 'blockading',
 'blocked',
 'blocking',
 'blocks',
 "bomb's",
 'bombard',
 'bombarded',
 'bombardier',
 'bombarding',
 'bombardment',
 'bombardments',
 'bombards',
 'bombed',
 'bomber',
 "bomber's",
 'bombers',
 'bombing',
 'bombings',
 'bombs',
 'bombshell',
 'bombshells',
 'bullet',
 'capabilities',
 'capability',
 'capitulate',
 'capitulated',
 'capitulating',
 'capitulation',
 'casualties',
 'casualty',
 'catastrophe',
 'catastrophes',
 'catastrophic',
 'catastrophically',
 'ceasefire',
 'chechnya',
 'chemical',
 'cluster',
 'coerce',
 'coerced',
 'coercing',
 'coercion',
 'coercive',
 'collapse',
 'collapsed',
 'collapses',
 'collapsible',
 'collapsing',
 'colonial',
 'combat',
 'combatant',
 'combatants',
 'combated',
 'combating',
 'combative',
 'combats',
 'combatting',
 'compelled',
 'compelling',
 'compellingly',
 'compels',
 'compromise',
 'concession',
 'conciliation',
 'conciliatory',
 'conflict',
 'conflicted',
 'conflicting',
 'conflicts',
 'contain',
 'contained',
 'containerized',
 'containing',
 'containment',
 'contains',
 'controllability',
 'controllable',
 'controlled',
 'controller',
 'controlling',
 'controls',
 'cooperate',
 'cooperated',
 'cooperates',
 'cooperating',
 'cooperation',
 'cooperative',
 'cooperatively',
 'counteract',
 'counteracted',
 'counteracting',
 'counteracts',
 'counterinsurgency',
 'counterinsurgent',
 'counterterrorism',
 'countervail',
 'countervailing',
 'coup',
 'crime',
 'crimea',
 'crimean',
 'crimes',
 'crimestoppers',
 'crimewatch',
 'criminal',
 "criminal's",
 'criminalisation',
 'criminalise',
 'criminalised',
 'criminality',
 'criminalization',
 'criminalize',
 'criminalized',
 'criminalizes',
 'criminalizing',
 'criminally',
 'criminals',
 'crisis',
 'critical',
 'cybersphere',
 'cyberwar',
 'damage',
 'damaged',
 'damages',
 'damaging',
 'dangerous',
 'dangerously',
 'dangers',
 'defence',
 'defenceless',
 'defences',
 'defend',
 'defended',
 'defender',
 "defender's",
 'defenders',
 'defending',
 'defends',
 'defense',
 'defenses',
 'destabilise',
 'destabilising',
 'destabilization',
 'destabilize',
 'destabilized',
 'destabilizing',
 'destructed',
 'destructible',
 'destructing',
 'destruction',
 'destructions',
 'destructive',
 'destructively',
 'destructiveness',
 'destructor',
 'deter',
 'deteriorate',
 'deteriorated',
 'deteriorates',
 'deteriorating',
 'deterioration',
 'determinant',
 'determine',
 'deterred',
 'deterrence',
 'deterrent',
 'deterrents',
 'deterring',
 'deters',
 'dictator',
 'dilemma',
 'disarmament',
 'disarmed',
 'disarming',
 'disarms',
 'disaster',
 'disease',
 'disintegrate',
 'disintegrated',
 'disintegrates',
 'disintegrating',
 'disintegration',
 'disobedience',
 'disobedient',
 'dispute',
 'division',
 'dominance',
 'dominant',
 'dominantly',
 'dominate',
 'dominated',
 'dominates',
 'dominating',
 'domination',
 'dominator',
 'dominators',
 'dominion',
 'dominions',
 'domino',
 'dominoes',
 'dominos',
 'drugs',
 'détente',
 'embargo',
 'emergency',
 'enemy',
 'escalation',
 'esculate',
 'evil',
 'existential',
 'expeditionary',
 'explosion',
 'explosions',
 'explosive',
 'explosively',
 'explosiveness',
 'explosives',
 'faction',
 'failed',
 'fear',
 'fightback',
 'fighter',
 "fighter's",
 'fighters',
 'fighting',
 'fights',
 'firearms',
 'fln',
 'forbid',
 'forbidden',
 'forbidding',
 'forbids',
 "force's",
 'forced',
 'forceful',
 'forcefully',
 'forces',
 'freedom',
 'friction',
 'fundamentalism',
 'fundamentalist',
 'fundamentalists',
 'gang',
 'gaza',
 'genocide',
 'globalization',
 'guerrilla',
 'guevara',
 'gulf',
 'hamas',
 'hazard',
 "hazard's",
 'hazardous',
 'hazards',
 'hegemonic',
 'hegemony',
 'hezbollah',
 'hiroshima',
 'homeland',
 'hostage',
 'hussein',
 'identity',
 'illegality',
 'illegally',
 'illegals',
 'illicit',
 'imminent',
 'imminently',
 'incumbent',
 'infiltrate',
 'infiltrated',
 'infiltrates',
 'infiltrating',
 'infiltration',
 'infiltrator',
 'infiltrators',
 'inhuman',
 'insecure',
 'insecurities',
 'insecurity',
 'insurgencies',
 'insurgency',
 'insurgent',
 'insurgents',
 'intelligence',
 'interdependence',
 'interdependent',
 'interdiction',
 'interpol',
 'intervene',
 'intervention',
 'invaded',
 'invader',
 'invaders',
 'invades',
 'ira',
 'iran',
 'iraq',
 'israel',
 "israel's",
 'israeli',
 'israelis',
 'israelite',
 'israelites',
 'israels',
 'killed',
 'killer',
 "killer's",
 'killers',
 'killing',
 'killings',
 'kills',
 'killswitch',
 'killzone',
 'kurd',
 'kurdish',
 'kurdistan',
 'kurds',
 'landmine',
 'law',
 "law's",
 'lawbreakers',
 'lawful',
 'lawfully',
 'lawfulness',
 'lawless',
 'lawlessness',
 'lawsuits',
 'lebanon',
 'liberate',
 'liberated',
 'liberates',
 'liberating',
 'liberation',
 'liberator',
 'liberators',
 'libya',
 'malacca',
 'militaries',
 'militarisation',
 'militarised',
 'militarism',
 'militarist',
 'militaristic',
 'militarization',
 'militarized',
 'military',
 "military's",
 'missile',
 'munitions',
 'muslims',
 'nagasaki',
 'narcotics',
 'nationalisation',
 'nationalise',
 'nationalised',
 'nationalism',
 'nationalist',
 'nationalistic',
 'nationalists',
 'nato',
 'nazi',
 'netwar',
 'nonproliferation',
 'nuclear',
 'offensive',
 'oil',
 'osce',
 'overwhelmed',
 'overwhelming',
 'overwhelmingly',
 'overwhelms',
 'pakistan',
 'palestine',
 'partisan',
 'police',
 'poverty',
 'power',
 'preempt',
 'preempted',
 'preemption',
 'preemptive',
 'preemptively',
 'preventable',
 'preventative',
 'prevented',
 'preventing',
 'prevention',
 'preventive',
 'prevents',
 'proliferate',
 'proliferated',
 'proliferating',
 'proliferation',
 'proliferative',
 'protected',
 'protecting',
 'protection',
 'protectionism',
 'protectionist',
 'protections',
 'protective',
 'protectively',
 'protector',
 'protectorate',
 'protectorates',
 'protectors',
 'protects',
 'punitive',
 'racism',
 'racist',
 'racists',
 'radical',
 'radicalisation',
 'radicalise',
 'radicalised',
 'radicalising',
 'radicalism',
 'radicalization',
 'radicalize',
 'radicalized',
 'radicalizing',
 'radically',
 'radicals',
 'rescue',
 'resist',
 'resistance',
 'resistances',
 'resistant',
 'resisted',
 'resisters',
 'resisting',
 'resistive',
 'resistivity',
 'resists',
 'resolution',
 'resources',
 'response',
 'retaliate',
 'retaliation',
 'revenge',
 'revolution',
 'rival',
 "rival's",
 'rivaled',
 'rivaling',
 'rivalled',
 'rivalling',
 'rivalries',
 'rivalry',
 'rivals',
 'rogue',
 'safe',
 'salt',
 'salw',
 'salwar',
 'sanctioned',
 'sanctioning',
 'sanctions',
 'sarin',
 'scarce',
 'scarcely',
 'scarcer',
 'scarcity',
 'seapower',
 'secure',
 'secured',
 'securely',
 'secures',
 'securing',
 'securities',
 'security',
 "security's",
 'separatism',
 'separatist',
 'separatists',
 'shock',
 'shortage',
 'shortages',
 'somalia',
 'sovereigns',
 'sovereignty',
 'stabilisation',
 'stabilise',
 'stabilised',
 'stabiliser',
 'stabilisers',
 'stabilising',
 'state',
 'strategic',
 'strategical',
 'strategically',
 'strategies',
 'strategise',
 'strategising',
 'strategize',
 'strategizing',
 'strategy',
 'strike',
 'suicide',
 'superpower',
 'surge',
 'surveillance',
 'syria',
 'tactical',
 'tactically',
 'tactician',
 'tactics',
 'target',
 'terror',
 'terrorise',
 'terrorised',
 'terrorising',
 'terrorism',
 'terrorist',
 "terrorist's",
 'terroristic',
 'terrorists',
 'terrorize',
 'terrorized',
 'terrorizes',
 'terrorizing',
 'terrors',
 'threaten',
 'threatened',
 'threatening',
 'threateningly',
 'threatens',
 'threats',
 'trafficked',
 'trafficker',
 'traffickers',
 'trafficking',
 'traffics',
 'transnational',
 'uncooperating',
 'uncooperative',
 'uncooperativley',
 'uprising',
 'values',
 'vietnam',
 'violence',
 'violent',
 'violently',
 'war',
 "war's",
 'warfare',
 'warfield',
 'warfighter',
 'warfighting',
 'wargame',
 'wargames',
 'warhead',
 'warheads',
 'warmonger',
 'warmongering',
 'warmongers',
 'warpath',
 'warplane',
 'warplanes',
 'wartime',
 'water',
 "weapon's",
 'weaponise',
 'weaponised',
 'weaponize',
 'weaponized',
 'weaponry',
 'weapons',
 'wmd',
 'wounded',
 'wounding',
 'wounds'}

In [25]:
# Now these words need to be split into the 3 dimensions (threat, urgency & just. extr power)

# First Threat, which was identified using the question: "Does this term, when used,
# characterise a referent object or situation as dangerous, harmful, destabilising or existentially risky?"
threat_SL = {
    'abm', 'afghanistan', 'aggression', 'airpower', 'alqaeda', 'antipersonnel',
    'apt', 'arab', 'armament', 'armaments', 'armed', 'armes', 'armies', 'arming',
    'armory', 'armour', 'armoured', 'armoury', 'arms', 'army', 'armys',
    'assassin', 'assassins', 'assassinate', 'assassinated', 'assassinating',
    'assassination', 'assassinations', 'assault', 'atomic', 'attacks', 'attacked',
    'attacker', 'attackers', 'attacking', 'authority', 'ballistic', 'battle',
    'biological', 'blockade', 'blockaded', 'blockades', 'blockading', 'blocked',
    'blocking', 'blocks', 'bombs', 'bombard', 'bombarded', 'bombardier',
    'bombarding', 'bombardment', 'bombardments', 'bombards', 'bombed', 'bomber',
    'bombers', 'bombing', 'bombings', 'bombshell', 'bombshells', 'bullet',
    'capabilities', 'capability', 'capitulate', 'capitulated', 'capitulating',
    'capitulation', 'casualties', 'casualty', 'catastrophe', 'catastrophes',
    'catastrophic', 'catastrophically', 'chechnya', 'chemical', 'cluster',
    'coerce', 'coerced', 'coercing', 'coercion', 'coercive', 'colonial',
    'combat', 'combatant', 'combatants', 'combated', 'combating', 'combative',
    'combats', 'combatting', 'conflict', 'conflicted', 'conflicting', 'conflicts',
    'controller', 'coup', 'crime', 'crimea', 'crimean', 'crimes', 'crimestoppers',
    'crimewatch', 'criminal', 'criminals', 'criminalisation', 'criminalise',
    'criminalised', 'criminality', 'criminalization', 'criminalize', 'criminalized',
    'criminalizes', 'criminalizing', 'criminally', 'crisis', 'cybersphere',
    'cyberwar', 'destabilise', 'destabilising', 'destabilization', 'destabilize',
    'destabilized', 'destabilizing', 'destructed', 'destructible', 'destructing',
    'destruction', 'destructions', 'destructive', 'destructively', 'destructiveness',
    'destructor', 'deteriorate', 'deteriorated', 'deteriorates', 'deteriorating',
    'deterioration', 'determinant', 'determine', 'dictator', 'dilemma', 'disaster',
    'disease', 'disintegrate', 'disintegrated', 'disintegrates', 'disintegrating',
    'disintegration', 'disobedient', 'disobedience', 'dispute', 'division',
    'dominance', 'dominant', 'dominantly', 'dominate', 'dominated', 'dominates',
    'dominating', 'domination', 'dominator', 'dominators', 'dominion', 'dominions',
    'domino', 'dominoes', 'dominos', 'drugs', 'enemy', 'evil', 'existential',
    'explosion', 'explosions', 'explosive', 'explosively', 'explosiveness',
    'explosives', 'faction', 'fighter', 'fighters', 'fighting', 'fights',
    'firearms', 'fln', 'forces', 'forceful', 'forcefully', 'friction',
    'fundamentalism', 'fundamentalist', 'fundamentalists', 'gang', 'gaza',
    'genocide', 'globalization', 'guerrilla', 'guevara', 'gulf', 'hamas',
    'hazard', 'hazards', 'hazardous', 'hegemonic', 'hegemony',
    'hezbollah', 'hiroshima', 'hussein', 'illegality', 'illegally', 'illegals',
    'illicit', 'infiltrate', 'infiltrated', 'infiltrates', 'infiltrating',
    'infiltration', 'infiltrator', 'infiltrators', 'inhuman', 'insecure',
    'insecurities', 'insecurity', 'insurgencies', 'insurgency', 'insurgent',
    'insurgents', 'interpol', 'invaded', 'invader', 'invaders', 'invades',
    'ira', 'iran', 'iraq', 'israel', 'israels', 'israeli', 'israelis',
    'israelite', 'israelites', 'killed', 'killer', 'killers', 'killing',
    'killings', 'kills', 'killswitch', 'killzone', 'kurd', 'kurdish',
    'kurdistan', 'kurds', 'landmine', 'lawbreakers', 'lawless', 'lawlessness',
    'lebanon', 'libya', 'militaries', 'militarisation', 'militarised',
    'militarism', 'militarist', 'militaristic', 'militarization', 'militarized',
    'military', 'militarys', 'missile', 'munitions', 'muslims', 'nagasaki',
    'narcotics', 'nationalisation', 'nationalise', 'nationalised', 'nationalism',
    'nationalist', 'nationalistic', 'nationalists', 'nato', 'nazi', 'netwar',
    'nuclear', 'offensive', 'osce', 'overwhelmed', 'overwhelming', 'overwhelms',
    'pakistan', 'palestine', 'partisan', 'police', 'power', 'proliferate',
    'proliferated', 'proliferating', 'proliferation', 'proliferative', 'racism',
    'racist', 'racists', 'radical', 'radicalisation', 'radicalise', 'radicalised',
    'radicalising', 'radicalism', 'radicalization', 'radicalize', 'radicalized',
    'radicalizing', 'radically', 'radicals', 'revolution', 'rival', 'rivals',
    'rivaled', 'rivaling', 'rivalled', 'rivalling', 'rivalries', 'rivalry',
    'rogue', 'salw', 'salwar', 'sarin', 'seapower', 'separatism', 'separatist',
    'separatists', 'shock', 'shortage', 'shortages', 'somalia', 'state',
    'strike', 'suicide', 'superpower', 'surge', 'surveillance', 'syria',
    'target', 'terror', 'terrorise', 'terrorised', 'terrorising', 'terrorism',
    'terrorist', 'terrorists', 'terroristic', 'terrorize', 'terrorized',
    'terrorizes', 'terrorizing', 'terrors', 'threaten', 'threatened',
    'threatening', 'threateningly', 'threatens', 'threats', 'trafficked',
    'trafficker', 'traffickers', 'trafficking', 'traffics', 'transnational',
    'uprising', 'vietnam', 'violence', 'violent', 'violently', 'war', 'wars',
    'warfare', 'warfield', 'warfighter', 'warfighting', 'wargame', 'wargames',
    'warhead', 'warheads', 'warmonger', 'warmongering', 'warmongers', 'warpath',
    'warplane', 'warplanes', 'wartime', 'weapons', 'weaponise', 'weaponised',
    'weaponize', 'weaponized', 'weaponry', 'wmd', 'wounded', 'wounding', 'wounds'
}

# Then urgency, for which I used the question: "Does this term compress time, increase necessity or reduce deliberative space?"
urgency_SL = {
    "armageddon", "collapse", "collapsed", "collapses", "collapsible", "collapsing",
    "critical", "damage", "damaged", "damages", "damaging", "dangerous",
    "dangerously", "dangers", "emergency", "esculate", "escalation",
    "imminent", "imminently", "intervene", "intervention", "overwhelmingly",
    "scarce", "scarcely", "scarcers", "scarcity"
}

# Justification of Extraordinary Power, which was identified with:
# "Does this term legitimise actions that exceed or suspend normal political, legal or administrative procedures?"
just_extr_power_SL = {
    'abate', 'abatement', 'alliance', 'anarchy', 'armistice', 'ceasefire',
    'compelled', 'compelling', 'compellingly', 'compels', 'compromise',
    'concession', 'conciliation', 'conciliatory', 'contain', 'contained', 'containment',
    'controllability', 'controllable', 'controlled', 'controlling', 'controls',
    'cooperate', 'cooperated', 'cooperates', 'cooperating', 'cooperation',
    'cooperative', 'cooperatively', 'counteract', 'counteracted', 'counteracting',
    'counteracts', 'counterinsurgency', 'counterinsurgent', 'counterterrorism',
    'countervail', 'countervailing', 'defence', 'defenceless', 'defences',
    'defend', 'defended', 'defender', 'defenders', 'defending', 'defends',
    'defense', 'defenses', 'deter', 'deterred', 'deterrence', 'deterrent',
    'deterrents', 'deterring', 'deters', 'disarmament', 'disarmed', 'disarming',
    'disarms', 'détente', 'embargo', 'expeditionary', 'failed', 'fear',
    'fightback', 'forbid', 'forbidden', 'forbidding', 'forbids',
    'forced', 'freedom', 'homeland', 'hostage', 'identity', 'incumbent',
    'intelligence', 'interdependence', 'interdependent', 'interdiction',
    'lawful', 'lawfully', 'lawfulness', 'liberate', 'liberated', 'liberates',
    'liberating', 'liberation', 'liberator', 'liberators', 'nonproliferation',
    'oil', 'poverty', 'preempt', 'preempted', 'preemption', 'preemptive',
    'preemptively', 'preventable', 'preventative', 'prevented', 'preventing',
    'prevention', 'preventive', 'prevents', 'protected', 'protecting',
    'protection', 'protectionism', 'protectionist', 'protections', 'protective',
    'protectively', 'protector', 'protectorate', 'protectorates', 'protectors',
    'protects', 'punitive', 'rescue', 'resist', 'resistance', 'resistances',
    'resistant', 'resisted', 'resisters', 'resisting', 'resistive', 'resistivity',
    'resists', 'resolution', 'resources', 'response', 'retaliation', 'revenge',
    'safe', 'sanctioned', 'sanctioning', 'sanctions', 'secure', 'secured',
    'securely', 'secures', 'securing', 'securities', 'security', 'securitys',
    'sovereigns', 'sovereignty', 'stabilisation', 'stabilise', 'stabilised',
    'stabiliser', 'stabilisers', 'stabilising', 'strategic', 'strategical',
    'strategically', 'strategies', 'strategise', 'strategising', 'strategize',
    'strategizing', 'strategy', 'tactical', 'tactically', 'tactician', 'tactics',
    'uncooperating', 'uncooperative', 'uncooperativley', 'values', 'retaliate'
}

# Note that although there are a lot of new words, many of these are variations of roots & spellings on the same word
print(f"Total words in threat_SL: {len(threat_SL)}")
print(f"Total words in urgency_SL: {len(urgency_SL)}")
print(f"Total words in just_extr_power_SL: {len(just_extr_power_SL)}")

Total words in threat_SL: 401
Total words in urgency_SL: 26
Total words in just_extr_power_SL: 173

In [26]:
# And now they need to be assigned categories using the same rules defined above for the seed lexicons
SL_threat_words_core_signals = {'genocide', 'assassin', 'assassins', 'assassinate', 'assassinated', 'assassinating', 'assassination', 'assassinations',
                                'assault', 'atomic', 'attacks', 'attacked', 'attacker', 'attackers', 'attacking', 'authority', 'ballistic', 'battle',
                                'bombs', 'bombard', 'bombarded', 'bombardier', 'bombarding', 'bombardment', 'bombardments', 'bombards', 'bombed', 'bomber',
                                'bombers', 'bombing', 'bombings', 'bombshell', 'bombshells', 'bullet', 'casualties', 'casualty', 'catastrophe', 'catastrophes',
                                'catastrophic', 'catastrophically', 'combat', 'combatant', 'combatants', 'combated', 'combating', 'combative', 'combats',
                                'combatting', 'conflict', 'conflicted', 'conflicting', 'conflicts', 'coup', 'cyberwar', 'fighter', 'fighters', 'fighting',
                                'fights', 'firearms', 'forces', 'infiltrate', 'infiltrated', 'infiltrates', 'infiltrating', 'infiltration', 'infiltrator',
                                'infiltrators', 'insurgencies', 'insurgency', 'insurgent', 'insurgents', 'invaded', 'invader', 'invaders', 'invades', 'killed',
                                'killer', 'killers', 'killing', 'killings', 'kills', 'killswitch', 'killzone', 'landmine', 'explosion', 'explosions', 'explosive',
                                'explosively', 'explosiveness', 'explosives', 'missile', 'netwar', 'nuclear', 'suicide', 'violence', 'violent', 'violently', 'war', 'wars',
                                'warfare', 'warfield', 'warfighter', 'warfighting', 'wargame', 'wargames', 'warheads', 'warmonger', 'warmongering', 'warmongers', 'warpath',
                                'warplane', 'warplanes', 'wartime', 'weapons', 'weaponise', 'weaponised', 'weaponize', 'weaponized', 'weaponry', 'warhead'}

SL_threat_words_secondary_signals = {'aggression', 'airpower', 'antipersonnel',
    'armament', 'armaments', 'armed', 'armes', 'armies', 'arming',
    'armory', 'armour', 'armoured', 'armoury', 'arms', 'army', 'armys',
    'biological', 'blockade', 'blockaded', 'blockades', 'blockading', 'blocked',
    'blocking', 'blocks',
    'capabilities', 'capability', 'capitulate', 'capitulated', 'capitulating',
    'capitulation', 'chemical', 'cluster',
    'coerce', 'coerced', 'coercing', 'coercion', 'coercive', 'colonial',
    'controller', 'crime', 'crimes', 'crimestoppers',
    'crimewatch', 'criminal', 'criminals', 'criminalisation', 'criminalise',
    'criminalised', 'criminality', 'criminalization', 'criminalize', 'criminalized',
    'criminalizes', 'criminalizing', 'criminally', 'crisis', 'cybersphere',
    'destabilise', 'destabilising', 'destabilization', 'destabilize',
    'destabilized', 'destabilizing', 'destructed', 'destructible', 'destructing',
    'destruction', 'destructions', 'destructive', 'destructively', 'destructiveness',
    'destructor', 'deteriorate', 'deteriorated', 'deteriorates', 'deteriorating',
    'deterioration', 'determinant', 'determine', 'dictator', 'dilemma', 'disaster',
    'disease', 'disintegrate', 'disintegrated', 'disintegrates', 'disintegrating',
    'disintegration', 'disobedient', 'disobedience', 'dispute', 'division',
    'dominance', 'dominant', 'dominantly', 'dominate', 'dominated', 'dominates',
    'dominating', 'domination', 'dominator', 'dominators', 'dominion', 'dominions',
    'domino', 'dominoes', 'dominos', 'drugs', 'enemy', 'evil', 'existential',
    'faction', 'forceful', 'forcefully', 'friction',
    'fundamentalism', 'fundamentalist', 'fundamentalists', 'gang', 'globalization',
    'hazard', 'hazards', 'hazardous', 'hegemonic', 'hegemony',
    'illegality', 'illegally', 'illegals',
    'illicit',  'inhuman', 'insecure',
    'insecurities', 'insecurity', 'interpol', 'lawbreakers', 'lawless', 'lawlessness',
    'militaries', 'militarisation', 'militarised',
    'militarism', 'militarist', 'militaristic', 'militarization', 'militarized',
    'military', 'militarys', 'munitions',
    'nationalisation', 'nationalise', 'nationalised', 'nationalism',
    'nationalist', 'nationalistic', 'nationalists',  'offensive', 'overwhelmed', 'overwhelming', 'overwhelms',
    'partisan', 'police', 'power', 'proliferate',
    'proliferated', 'proliferating', 'proliferation', 'proliferative', 'racism',
    'racist', 'racists', 'radical', 'radicalisation', 'radicalise', 'radicalised',
    'radicalising', 'radicalism', 'radicalization', 'radicalize', 'radicalized',
    'radicalizing', 'radically', 'radicals', 'revolution', 'rival', 'rivals',
    'rivaled', 'rivaling', 'rivalled', 'rivalling', 'rivalries', 'rivalry',
    'rogue',  'seapower', 'separatism', 'separatist',
    'separatists', 'shock', 'shortage', 'shortages', 'state',
    'strike', 'superpower', 'surge', 'surveillance', 'syria',
    'target', 'terror', 'terrorise', 'terrorised', 'terrorising', 'terrorism',
    'terrorist', 'terrorists', 'terroristic', 'terrorize', 'terrorized',
    'terrorizes', 'terrorizing', 'terrors', 'threaten', 'threatened',
    'threatening', 'threateningly', 'threatens', 'threats', 'trafficked',
    'trafficker', 'traffickers', 'trafficking', 'traffics', 'transnational',
    'uprising', 'wounded', 'wounding', 'wounds'}

SL_threat_words_contextual_signals = {'abm', 'afghanistan', 'alqaeda', 'apt', 'arab', 'crimea', 'crimean', 'fln', 'gaza', 'guerrilla', 'guevara', 'gulf',
    'hamas', 'hezbollah', 'hiroshima', 'hussein', 'ira', 'iran', 'iraq', 'israel', 'israels', 'israeli', 'israelis',
    'israelite', 'israelites', 'kurd', 'kurdish', 'kurdistan', 'kurds', 'lebanon', 'libya', 'muslims', 'nagasaki', 'narcotics',
    'nato', 'nazi', 'pakistan', 'palestine', 'salw', 'vietnam', 'osce', 'somalia', 'salwar', 'sarin', 'wmd', 'chechnya'}


SL_urgency_words_core_signals = {"armageddon", "collapse", "collapsed", "collapses", "collapsible", "collapsing", "imminent", "imminently"}
SL_urgency_words_secondary_signals = {"critical", "damage", "damaged", "damages", "damaging", "dangerous", "dangerously", "dangers", "emergency", "esculate",
    "escalation", "intervene", "intervention", "overwhelmingly", "scarce", "scarcely", "scarcers", "scarcity"}
SL_urgency_words_contextual_signals = {}


SL_justification_of_extr_power_words_core_signals = {'anarchy', 'counterinsurgency', 'counterinsurgent', 'counterterrorism', 'countervail', 'countervailing',
    'defences', 'counteract', 'counteracted', 'counteracting', 'counteracts', 'defence',
    'defenceless', 'defend', 'defended', 'defender', 'defenders', 'defending', 'defends', 'defense',
    'defenses', 'deter', 'deterred', 'deterrence', 'deterrent', 'deterrents', 'deterring', 'deters',
    'disarmament', 'disarmed', 'disarming', 'disarms', 'fightback', 'forbid', 'forbidden', 'forbidding', 'forbids',
    'forced', 'freedom', 'homeland', 'hostage', 'interdiction', 'liberate', 'liberated', 'liberates',
    'liberating', 'liberation', 'liberator', 'liberators', 'nonproliferation', 'punitive', 'rescue', 'resist',
    'resistance', 'resistances', 'resistant', 'resisted', 'resisters', 'resisting', 'resistive', 'resistivity',
    'resists', 'resolution', 'retaliation', 'retaliate', 'revenge', 'sanctioned', 'sanctioning', 'sanctions',
    'stabilisation', 'stabilise', 'stabilised', 'stabiliser', 'stabilisers', 'stabilising', 'tactical',
    'tactically', 'tactician', 'tactics'}
#SL_justification_of_extr_power_terms_core_signals = {'fight back'}

SL_justification_of_extr_power_words_secondary_signals = {'abate', 'abatement', 'alliance', 'compelled', 'compelling', 'compellingly', 'compels', 'compromise',
    'contain', 'contained', 'containment', 'controllability', 'controllable', 'controlled', 'controlling',
    'controls', 'cooperate', 'cooperated', 'cooperates', 'cooperating', 'cooperation', 'cooperative',
    'cooperatively', 'fear', 'incumbent', 'interdependence', 'interdependent', 'preempt', 'preempted', 'preemption', 'preemptive',
    'preemptively', 'preventable', 'preventative', 'prevented', 'preventing', 'prevention', 'preventive',
    'prevents', 'protected', 'protecting', 'protection', 'protectionism', 'protectionist', 'protections', 'protective',
    'protectively', 'protector', 'protectorate', 'protectorates', 'protectors', 'protects', 'response',
    'safe', 'secure', 'secured', 'securely', 'secures', 'securing', 'sovereigns', 'sovereignty',
    'strategic', 'strategical', 'strategically', 'strategies', 'strategise', 'strategising', 'strategize',
    'strategizing', 'strategy', 'values', 'uncooperative', 'uncooperating', 'uncooperativley'}

SL_justification_of_extr_power_words_contextual_signals = {'armistice', 'ceasefire', 'concession', 'conciliation', 'conciliatory', 'détente', 'embargo',
    'expeditionary', 'failed', 'identity', 'intelligence', 'lawful', 'lawfully', 'lawfulness', 'oil',
    'poverty', 'resources', 'securities', 'security', 'securitys'}

In [27]:
# Then these are to be combined assigned signals and combined with the seed word lexicons

# 1st I categorise SL (seed lexicon) Threat Words
SL_threat_seed_lexicon_words_signal_categories = categorise_and_report_lexicon(
    threat_SL, SL_threat_words_core_signals, SL_threat_words_secondary_signals, SL_threat_words_contextual_signals, "SL threat words")

# then urgency
SL_urgency_seed_lexicon_words_signal_categories = categorise_and_report_lexicon(
    urgency_SL, SL_urgency_words_core_signals, SL_urgency_words_secondary_signals, SL_threat_words_contextual_signals, "SL urgency words")

# finally justification of extraordinary power
SL_justification_of_extr_power_seed_lexicon_words_signal_categories = categorise_and_report_lexicon(
    just_extr_power_SL, SL_justification_of_extr_power_words_core_signals, SL_justification_of_extr_power_words_secondary_signals, SL_justification_of_extr_power_words_contextual_signals, "SL justification words")

All good in SL threat words, I've assigned each term a signal category
All good in SL urgency words, I've assigned each term a signal category
All good in SL justification words, I've assigned each term a signal category

In [28]:
# now I combine SL signal categories with existing seed lexicon signal categories

# Threat words
threat_seed_lexicon_words_signal_categories.update(SL_threat_seed_lexicon_words_signal_categories)

# Urgency words
urgency_seed_lexicon_words_signal_categories.update(SL_urgency_seed_lexicon_words_signal_categories)

# Justification of Extraordinary Power words
justification_of_extr_power_seed_lexicon_words_signal_categories.update(SL_justification_of_extr_power_seed_lexicon_words_signal_categories)

print("Combined signal categories successfully!")
print(f"The updated Threat words count is: {len(threat_seed_lexicon_words_signal_categories)}")
print(f"& Urgency word count is at: {len(urgency_seed_lexicon_words_signal_categories)}")
print(f"& Justification at: {len(justification_of_extr_power_seed_lexicon_words_signal_categories)}")

Combined signal categories successfully!
The updated Threat words count is: 707
& Urgency word count is at: 79
& Justification at: 331

# 3. Exporting lexicons ready for SBERT expansion
At this stage, the lexicon is substaintial and highly targeted. I've gone from seed dictionary -> expanded with known securitisation literature. Now the final lexicon is to be exported with the aim of now searching for semantically similar words in the same neighbourhoods as the current lexicon words, which will be done with SBERT.

Expansion will prioritise human-in-the-loop oversight to ensure the lexcion dimensions are expanded precisely and minimally. Importantly, embedding-based expansion will not alter the theory-derived lexicon above, which is now frozen.

In [ ]:
# Now these are exported to an excel for SBERT expansion (in another collab file)
threat_data = {"Term": list(threat_seed_lexicon_words_signal_categories.keys()) + list(threat_seed_lexicon_terms_signal_categories.keys()),
               "Signal Type": list(threat_seed_lexicon_words_signal_categories.values()) + list(threat_seed_lexicon_terms_signal_categories.values())}
df_threat= pd.DataFrame(threat_data)

urgency_data= {"Term": list(urgency_seed_lexicon_words_signal_categories.keys()) + list(urgency_seed_lexicon_terms_signal_categories.keys()),
                "Signal Type": list(urgency_seed_lexicon_words_signal_categories.values()) + list(urgency_seed_lexicon_terms_signal_categories.values())}
df_urgency= pd.DataFrame(urgency_data)

justification_data= {"Term": list(justification_of_extr_power_seed_lexicon_words_signal_categories.keys()) + list(justification_of_extr_power_seed_lexicon_terms_signal_categories.keys()),
                      "Signal Type": list(justification_of_extr_power_seed_lexicon_words_signal_categories.values()) + list(justification_of_extr_power_seed_lexicon_terms_signal_categories.values())}
df_justification= pd.DataFrame(justification_data)

# here I'm converting the 'Signal Type' col to a categorical type with custom order and sorting the dfs
df_threat['Signal Type']= pd.Categorical(df_threat['Signal Type'], categories=tier_order_to_display, ordered=True)
df_threat= df_threat.sort_values('Signal Type').reset_index(drop=True)

df_urgency['Signal Type']= pd.Categorical(df_urgency['Signal Type'], categories=tier_order_to_display, ordered=True)
df_urgency = df_urgency.sort_values('Signal Type').reset_index(drop=True)

df_justification['Signal Type']= pd.Categorical(df_justification['Signal Type'], categories=tier_order_to_display, ordered=True)
df_justification= df_justification.sort_values('Signal Type').reset_index(drop=True)

created_lexicon_output_filename= "securitisation_lexicon.xlsx"

with pd.ExcelWriter(created_lexicon_output_filename, engine='xlsxwriter') as writer:
    df_threat.to_excel(writer, sheet_name='Threat Lexicon', index=False)
    df_urgency.to_excel(writer, sheet_name='Urgency Lexicon', index=False)
    df_justification.to_excel(writer, sheet_name='Justification Lexicon', index=False)

print(f"Lexicons exported to {created_lexicon_output_filename} successfully!")

## References I used
Buzan, Barry, Ole Wæver, and Jaap de Wilde. *Security: A New Framework for Analysis*. Boulder, CO: Lynne Rienner Publishers, 1998.

Baele, S. J., & Rousseau, E. (2022). At war or saving lives? On the securitizing semantic repertoires of Covid-19. International Relations, 37(2), 201–227. https://doi.org/10.1177/00471178221122957

‌Otukoya, T. A. (2024). The securitization theory. International Journal of Science and Research Archive, 11(1), 1747–1755. https://doi.org/10.30574/ijsra.2024.11.1.0225

Ahmad, Y., & Bouwman, B. (2025). MA Thesis Securitisation and Nubian Erasure in Postcolonial Egypt. Retrieved January 16, 2026, from https://studenttheses.uu.nl/bitstream/handle/20.500.12932/50484/Securitisation%20and%20Nubian%20Erasure%20in%20Postcolonial%20Egypt%20-%20Youssef%20Ahmad.pdf?sequence=1&isAllowed=y

State of Exception. (2003). http://pdf-objects.com/files/US-English-PDF-Object.pdf

Flohr, M. (2025, March 31). Key Concept: Securitization (Copenhagen School). Critical Legal Thinking. https://criticallegalthinking.com/2025/03/31/key-concept-securitization-copenhagen-school/

‌Baele, S. J., & Sterck, O. C. (2014). Diagnosing the Securitisation of Immigration at the EU Level: A New Method for Stronger Empirical Claims. Political Studies, 63(5), 1120–1139. https://doi.org/10.1111/1467-9248.12147

Duan, Z., Shao, A., Hu, Y., Lee, H., Liao, X., Suh, Y. J., Kim, J., Yang, K.-C., Chen, K., & Yang, S. (2025). Constructing Vec-tionaries to Extract Message Features from Texts: A Case Study of Moral Content. Political Analysis, 33(4), 425–445. https://doi.org/10.1017/pan.2025.6

S. Stetter, E. Herschinger, T. Teichler, and M. Albert, “Conflicts about water: Securitizations in a global context,” Jstor.org, 2026, doi: https://doi.org/10.2307/45084673.
‌